unit pweb.lib.webview;
{ This unit is automatically generated by ChetCLI 1.0.0.
  libclang: clang version 14.0.0
  Based on Chet by Erik van Bilsen:
    https://github.com/neslib/Chet }

{ Generated from webview/webview @ cbbdee44afff22867de9fd88a9fc8350d9bdd399
  (pin recorded in webview.lock; regenerate ONLY via
  tools/regen-webview-binding.ps1 -- never edit by hand). }

{$MODE OBJFPC}{$H+}
{$MINENUMSIZE 4}
{$PACKRECORDS C}

interface

const
  {$IF Defined(WIN64)}
  LIB_WEBVIEW = 'webview.dll';
  _PU = '';
  {$ELSEIF Defined(DARWIN) and Defined(CPUAARCH64) and not Defined(IOS)}
  LIB_WEBVIEW = 'libwebview.dylib';
  _PU = '';
  {$ELSEIF Defined(DARWIN) and Defined(CPUX64) and not Defined(IOS)}
  LIB_WEBVIEW = 'libwebview.dylib';
  _PU = '';
  {$ELSEIF Defined(LINUX)}
  LIB_WEBVIEW = 'libwebview.so';
  _PU = '';
  {$ELSE}
    {$MESSAGE Error 'Unsupported platform'}
  {$ENDIF}

type
  webview_error_t = Integer;
  Pwebview_error_t = ^webview_error_t;

const
  WEBVIEW_ERROR_MISSING_DEPENDENCY = -5;
  WEBVIEW_ERROR_CANCELED = -4;
  WEBVIEW_ERROR_INVALID_STATE = -3;
  WEBVIEW_ERROR_INVALID_ARGUMENT = -2;
  WEBVIEW_ERROR_UNSPECIFIED = -1;
  WEBVIEW_ERROR_OK = 0;
  WEBVIEW_ERROR_DUPLICATE = 1;
  WEBVIEW_ERROR_NOT_FOUND = 2;

type
  webview_native_handle_kind_t = Integer;
  Pwebview_native_handle_kind_t = ^webview_native_handle_kind_t;

const
  WEBVIEW_NATIVE_HANDLE_KIND_UI_WINDOW = 0;
  WEBVIEW_NATIVE_HANDLE_KIND_UI_WIDGET = 1;
  WEBVIEW_NATIVE_HANDLE_KIND_BROWSER_CONTROLLER = 2;

type
  webview_hint_t = Integer;
  Pwebview_hint_t = ^webview_hint_t;

const
  WEBVIEW_HINT_NONE = 0;
  WEBVIEW_HINT_MIN = 1;
  WEBVIEW_HINT_MAX = 2;
  WEBVIEW_HINT_FIXED = 3;

type
  // Forward declarations
  Pwebview_version_t = ^webview_version_t;
  Pwebview_version_info_t = ^webview_version_info_t;

  webview_version_t = record
    major: Cardinal;
    minor: Cardinal;
    patch: Cardinal;
  end;

  webview_version_info_t = record
    version: webview_version_t;
    version_number: array [0..31] of AnsiChar;
    pre_release: array [0..47] of AnsiChar;
    build_metadata: array [0..47] of AnsiChar;
  end;

  webview_t = Pointer;

function webview_create(debug: Integer; window: Pointer): webview_t; cdecl;
  external LIB_WEBVIEW name _PU + 'webview_create';

function webview_destroy(w: webview_t): webview_error_t; cdecl;
  external LIB_WEBVIEW name _PU + 'webview_destroy';

function webview_run(w: webview_t): webview_error_t; cdecl;
  external LIB_WEBVIEW name _PU + 'webview_run';

function webview_terminate(w: webview_t): webview_error_t; cdecl;
  external LIB_WEBVIEW name _PU + 'webview_terminate';

type
  webview_dispatch_fn = procedure(w: webview_t; arg: Pointer); cdecl;

function webview_dispatch(w: webview_t; fn: webview_dispatch_fn; arg: Pointer): webview_error_t; cdecl;
  external LIB_WEBVIEW name _PU + 'webview_dispatch';

function webview_get_window(w: webview_t): Pointer; cdecl;
  external LIB_WEBVIEW name _PU + 'webview_get_window';

function webview_get_native_handle(w: webview_t; kind: webview_native_handle_kind_t): Pointer; cdecl;
  external LIB_WEBVIEW name _PU + 'webview_get_native_handle';

function webview_set_title(w: webview_t; const title: PAnsiChar): webview_error_t; cdecl;
  external LIB_WEBVIEW name _PU + 'webview_set_title';

function webview_set_size(w: webview_t; width: Integer; height: Integer; hints: webview_hint_t): webview_error_t; cdecl;
  external LIB_WEBVIEW name _PU + 'webview_set_size';

function webview_navigate(w: webview_t; const url: PAnsiChar): webview_error_t; cdecl;
  external LIB_WEBVIEW name _PU + 'webview_navigate';

function webview_set_html(w: webview_t; const html: PAnsiChar): webview_error_t; cdecl;
  external LIB_WEBVIEW name _PU + 'webview_set_html';

function webview_init(w: webview_t; const js: PAnsiChar): webview_error_t; cdecl;
  external LIB_WEBVIEW name _PU + 'webview_init';

function webview_eval(w: webview_t; const js: PAnsiChar): webview_error_t; cdecl;
  external LIB_WEBVIEW name _PU + 'webview_eval';

type
  webview_bind_fn = procedure(const id: PAnsiChar; const req: PAnsiChar; arg: Pointer); cdecl;

function webview_bind(w: webview_t; const name: PAnsiChar; fn: webview_bind_fn; arg: Pointer): webview_error_t; cdecl;
  external LIB_WEBVIEW name _PU + 'webview_bind';

function webview_unbind(w: webview_t; const name: PAnsiChar): webview_error_t; cdecl;
  external LIB_WEBVIEW name _PU + 'webview_unbind';

function webview_return(w: webview_t; const id: PAnsiChar; status: Integer; const result: PAnsiChar): webview_error_t; cdecl;
  external LIB_WEBVIEW name _PU + 'webview_return';

function webview_version(): Pwebview_version_info_t; cdecl;
  external LIB_WEBVIEW name _PU + 'webview_version';

implementation

end.
