unit pweb.test.assets;

{ mormot.core.test cases for CAP-4: shared canonical-path validation,
  deterministic MIME, and Folder/ZIP IAssetStore parity.

  One canonical fixture corpus is generated at Setup time (never
  committed - the repository .gitignore swallows *.txt and binary
  fixtures would be opaque anyway) and served through BOTH stores:
  byte and ContentType identity is asserted for every entry, plus the
  hostile-path matrix, exact Windows case, hostile crafted archives,
  folder root confinement (junction escape), zero-byte and
  NUL-containing assets, repeated and concurrent reads.

  Hostile archives are crafted as raw ZIP bytes: TZipWrite normalizes
  path delimiters on write, so it cannot produce the backslash/
  traversal/duplicate forms these tests must prove rejected. }

{$I mormot.defines.inc}

interface

uses
  {$ifdef OSWINDOWS}
  windows,
  {$endif OSWINDOWS}
  sysutils,
  classes,
  mormot.core.base,
  mormot.core.os,
  mormot.core.unicode,
  mormot.core.text,
  mormot.core.test,
  mormot.core.zip,
  mormot.lib.z,
  pweb.assets.intf,
  pweb.assets.support,
  pweb.assets.folder,
  pweb.assets.zip;

type
  /// CAP-4 asset-system cases: validation, MIME, Folder/ZIP parity
  TTestAssetStores = class(TSynTestCase)
  protected
    fRoot: TFileName; // temp folder-store root (canonical corpus)
    fOutside: TFileName; // temp dir OUTSIDE the root, junction target
    fZipBytes: RawByteString; // canonical corpus as a ZIP archive
    fZipFile: TFileName; // same archive written to disk
    fFolder: IAssetStore;
    fZip: IAssetStore;
    fJunction: TFileName; // '' if junction creation failed
    procedure Setup; override;
    procedure CleanUp; override;
    {$ifdef OSWINDOWS}
    procedure CheckShortNameAlias;
    {$endif OSWINDOWS}
  published
    /// canonical logical-path rules, MIME table, percent decode, URI parse
    procedure CanonicalPathRules;
    /// identical bytes and ContentType from Folder and ZIP stores
    procedure CorpusParity;
    /// hostile inputs return False from both stores
    procedure HostilePathMatrix;
    /// exact case-sensitive lookup on the Windows filesystem and in ZIP
    procedure ExactCaseSensitivity;
    /// duplicate/traversal/backslash/absolute/case-colliding archives fail
    procedure HostileArchives;
    /// misconfigured store roots and archives fail at construction
    procedure ConstructorFailures;
    /// folder resolution never follows a reparse point out of its root
    procedure RootConfinement;
    /// a UTF-8 (non-ASCII) asset name serves through both stores
    procedure NonAsciiNames;
    /// repeated and concurrent reads stay deterministic
    procedure RepeatedAndConcurrentReads;
    /// concurrency over a file-backed archive large enough to use the
    /// shared seekable source - the path the private lock exists for
    procedure FileBackedArchiveConcurrency;
  end;

/// build a parseable ZIP whose STORED zero-byte entries carry exactly
// the supplied raw names (hostile names included) - full control over
// stored bytes, beyond what TZipWrite can express; shared with the
// CAP-6 bundle suite for tamper fixtures
function BuildRawZip(const Names: array of RawByteString): RawByteString;

/// same raw-ZIP crafting with per-entry STORED contents (correct CRCs)
// - Contents may be shorter than Names; missing entries are zero-byte
function BuildRawZipEx(const Names: array of RawByteString;
  const Contents: array of RawByteString): RawByteString;

/// remove a test directory tree (junction-aware, never recursing into
// reparse points) - shared test plumbing
procedure RmTree(const Dir: TFileName);

implementation

type
  TCorpusEntry = record
    Name: RawUtf8;
    Mime: RawUtf8;
  end;

const
  // fixture corpus: names + expected deterministic MIME; contents are
  // generated by CorpusContent() below
  CORPUS: array[0..6] of TCorpusEntry = (
    (Name: 'index.html'; Mime: 'text/html; charset=utf-8'),
    (Name: 'assets/app.js'; Mime: 'text/javascript; charset=utf-8'),
    (Name: 'assets/app.css'; Mime: 'text/css; charset=utf-8'),
    (Name: 'assets/CamelCase.js'; Mime: 'text/javascript; charset=utf-8'),
    (Name: 'assets/empty.bin'; Mime: 'application/octet-stream'),
    (Name: 'assets/nested/data.bin'; Mime: 'application/octet-stream'),
    (Name: 'notes.txt'; Mime: 'text/plain; charset=utf-8'));

function CorpusContent(const Name: RawUtf8): RawByteString;
var
  i: PtrInt;
begin
  if Name = 'index.html' then
    Result := '<!doctype html><html><body>corpus</body></html>'
  else if Name = 'assets/app.js' then
    Result := 'console.log("corpus");' + #10
  else if Name = 'assets/app.css' then
    Result := 'body{margin:0}'
  else if Name = 'assets/CamelCase.js' then
    Result := 'export const x=1;'
  else if Name = 'assets/empty.bin' then
    Result := '' // zero-byte asset must round-trip
  else if Name = 'assets/nested/data.bin' then
  begin
    // binary content including NUL and every byte value
    SetLength(Result, 4096);
    for i := 1 to Length(Result) do
      Result[i] := AnsiChar((i - 1) and 255);
  end
  else if Name = 'notes.txt' then
    Result := 'plain text'
  else
    Result := '';
end;

{ raw ZIP crafting - full control over stored entry names }

procedure AppendWord(var s: RawByteString; v: Word);
begin
  SetLength(s, Length(s) + 2);
  PWord(@s[Length(s) - 1])^ := v;
end;

procedure AppendCardinal(var s: RawByteString; v: Cardinal);
begin
  SetLength(s, Length(s) + 4);
  PCardinal(@s[Length(s) - 3])^ := v;
end;

function BuildRawZipEx(const Names: array of RawByteString;
  const Contents: array of RawByteString): RawByteString;
var
  central, c: RawByteString;
  offsets, crcs: array of Cardinal;
  i: PtrInt;
  cdOffset: Cardinal;
begin
  // fixture-builder guards: the 16/32-bit ZIP header fields must
  // never silently truncate what a test believes it crafted
  if Length(Contents) > Length(Names) then
    raise Exception.Create('BuildRawZipEx: more Contents than Names');
  Result := '';
  central := '';
  SetLength(offsets, Length(Names));
  SetLength(crcs, Length(Names));
  for i := 0 to High(Names) do
  begin
    if Length(Names[i]) > 65535 then
      raise Exception.Create('BuildRawZipEx: name exceeds 16-bit field');
    if i <= High(Contents) then
      c := Contents[i]
    else
      c := '';
    if Int64(Length(c)) > Int64(High(Cardinal)) then
      raise Exception.Create('BuildRawZipEx: content exceeds 32-bit field');
    if c = '' then
      crcs[i] := 0
    else
      crcs[i] := crc32(0, pointer(c), Length(c));
    offsets[i] := Length(Result);
    AppendCardinal(Result, $04034b50); // local file header
    AppendWord(Result, 20); // version needed
    AppendWord(Result, 0);  // flags
    AppendWord(Result, 0);  // method = STORED
    AppendWord(Result, 0);  // time
    AppendWord(Result, 0);  // date
    AppendCardinal(Result, crcs[i]);
    AppendCardinal(Result, Length(c)); // compressed size
    AppendCardinal(Result, Length(c)); // uncompressed size
    AppendWord(Result, Length(Names[i]));
    AppendWord(Result, 0); // extra len
    Result := Result + Names[i] + c;
  end;
  cdOffset := Length(Result);
  for i := 0 to High(Names) do
  begin
    if i <= High(Contents) then
      c := Contents[i]
    else
      c := '';
    AppendCardinal(central, $02014b50); // central directory header
    AppendWord(central, 20); // version made by
    AppendWord(central, 20); // version needed
    AppendWord(central, 0);  // flags
    AppendWord(central, 0);  // method
    AppendWord(central, 0);  // time
    AppendWord(central, 0);  // date
    AppendCardinal(central, crcs[i]);
    AppendCardinal(central, Length(c)); // compressed size
    AppendCardinal(central, Length(c)); // uncompressed size
    AppendWord(central, Length(Names[i]));
    AppendWord(central, 0); // extra len
    AppendWord(central, 0); // comment len
    AppendWord(central, 0); // disk number
    AppendWord(central, 0); // internal attrs
    AppendCardinal(central, 0); // external attrs
    AppendCardinal(central, offsets[i]);
    central := central + Names[i];
  end;
  Result := Result + central;
  AppendCardinal(Result, $06054b50); // end of central directory
  AppendWord(Result, 0); // disk
  AppendWord(Result, 0); // cd disk
  AppendWord(Result, Length(Names)); // entries on disk
  AppendWord(Result, Length(Names)); // entries total
  AppendCardinal(Result, Length(central));
  AppendCardinal(Result, cdOffset);
  AppendWord(Result, 0); // comment len
end;

function BuildRawZip(const Names: array of RawByteString): RawByteString;
begin
  Result := BuildRawZipEx(Names, []);
end;

// one STORED entry whose central directory CLAIMS the given
// uncompressed size - for testing the construction-time size ceiling
function BuildRawZipSizedEntry(const Name: RawByteString;
  DeclaredFullSize: Cardinal): RawByteString;
var
  central: RawByteString;
begin
  Result := '';
  AppendCardinal(Result, $04034b50); // local file header
  AppendWord(Result, 20);
  AppendWord(Result, 0);
  AppendWord(Result, 0); // STORED
  AppendWord(Result, 0);
  AppendWord(Result, 0);
  AppendCardinal(Result, 0); // crc32
  AppendCardinal(Result, 0); // compressed size
  AppendCardinal(Result, DeclaredFullSize);
  AppendWord(Result, Length(Name));
  AppendWord(Result, 0);
  Result := Result + Name;
  central := '';
  AppendCardinal(central, $02014b50);
  AppendWord(central, 20);
  AppendWord(central, 20);
  AppendWord(central, 0);
  AppendWord(central, 0);
  AppendWord(central, 0);
  AppendWord(central, 0);
  AppendCardinal(central, 0);
  AppendCardinal(central, 0);
  AppendCardinal(central, DeclaredFullSize);
  AppendWord(central, Length(Name));
  AppendWord(central, 0);
  AppendWord(central, 0);
  AppendWord(central, 0);
  AppendWord(central, 0);
  AppendCardinal(central, 0);
  AppendCardinal(central, 0); // local offset
  central := central + Name;
  Result := Result + central;
  AppendCardinal(Result, $06054b50);
  AppendWord(Result, 0);
  AppendWord(Result, 0);
  AppendWord(Result, 1);
  AppendWord(Result, 1);
  AppendCardinal(Result, Length(central));
  // central-directory offset = local header + name, i.e. everything
  // before central: current length minus central minus the 16 EOCD
  // bytes already appended
  AppendCardinal(Result, Length(Result) - Length(central) - 16);
  AppendWord(Result, 0);
end;

procedure RmTree(const Dir: TFileName);
var
  sr: TSearchRec;
begin
  if (Dir = '') or
     not DirectoryExists(Dir) then
    exit;
  if FindFirst(Dir + PathDelim + '*', faAnyFile{%H-}, sr) = 0 then
  begin
    repeat
      if (sr.Name = '.') or
         (sr.Name = '..') then
        continue;
      if (sr.Attr and faDirectory{%H-}) <> 0 then
      begin
        if (sr.Attr and $00000400) <> 0 then // junction: do not recurse
          RemoveDir(Dir + PathDelim + sr.Name)
        else
          RmTree(Dir + PathDelim + sr.Name);
      end
      else
        SysUtils.DeleteFile(Dir + PathDelim + sr.Name);
    until FindNext(sr) <> 0;
    FindClose(sr);
  end;
  RemoveDir(Dir);
end;

procedure WriteCorpusFile(const Root: TFileName; const Name: RawUtf8);
var
  full: TFileName;
  i: PtrInt;
  content: RawByteString;
begin
  full := Root + PathDelim;
  for i := 1 to Length(Name) do
    if Name[i] = '/' then
      full := full + PathDelim
    else
      full := full + Name[i];
  ForceDirectories(ExtractFileDir(full));
  content := CorpusContent(Name);
  if not FileFromString(content, full) then
    raise Exception.CreateFmt('cannot write fixture %s', [full]);
end;

procedure TTestAssetStores.Setup;
var
  base, cmd, comspec: TFileName;
  i: PtrInt;
  mem: TMemoryStream;
  zw: TZipWrite;
  content: RawByteString;
  code: Integer;
begin
  base := GetTempDir + 'pweb-cap4-' + IntToStr(GetCurrentProcessId);
  fRoot := base + PathDelim + 'dist';
  fOutside := base + PathDelim + 'outside';
  RmTree(base);
  ForceDirectories(fRoot);
  ForceDirectories(fOutside);
  for i := 0 to High(CORPUS) do
    WriteCorpusFile(fRoot, CORPUS[i].Name);
  // a secret outside the root, reachable only through an escape
  if not FileFromString('outside-secret', fOutside + PathDelim + 'secret.bin') then
    raise Exception.Create('cannot write outside fixture');
  // canonical archive built from the same corpus
  mem := TMemoryStream.Create;
  try
    zw := TZipWrite.Create(mem);
    try
      for i := 0 to High(CORPUS) do
      begin
        content := CorpusContent(CORPUS[i].Name);
        zw.AddDeflated(Utf8ToString(CORPUS[i].Name),
          pointer(content), Length(content));
      end;
    finally
      zw.Free;
    end;
    SetString(fZipBytes, PAnsiChar(mem.Memory), mem.Size);
  finally
    mem.Free;
  end;
  fZipFile := base + PathDelim + 'app.zip';
  if not FileFromString(fZipBytes, fZipFile) then
    raise Exception.Create('cannot write fixture archive');
  fFolder := TFolderAssetStore.Create(fRoot);
  fZip := TZipAssetStore.CreateFromBuffer(fZipBytes);
  // junction inside the root pointing outside it (no admin needed)
  fJunction := fRoot + PathDelim + 'outlink';
  code := -1;
  {$ifdef OSWINDOWS}
  comspec := SysUtils.GetEnvironmentVariable('COMSPEC');
  if comspec = '' then
    comspec := 'C:\Windows\System32\cmd.exe';
  cmd := '/c mklink /J "' + fJunction + '" "' + fOutside + '" >nul';
  try
    code := ExecuteProcess(comspec, cmd, []);
  except
    code := -1;
  end;
  {$endif OSWINDOWS}
  if code <> 0 then
    fJunction := '';
end;

procedure TTestAssetStores.CleanUp;
begin
  fFolder := nil;
  fZip := nil;
  RmTree(GetTempDir + 'pweb-cap4-' + IntToStr(GetCurrentProcessId));
end;

procedure TTestAssetStores.CanonicalPathRules;
const
  BAD: array[0..30] of RawUtf8 = (
    '', '.', '..', '../x', './x', 'assets/../x', 'assets//x',
    'a\b', '/absolute', 'C:/x', '//server/share', 'x.txt:ads',
    'NUL', 'CON', 'nul.txt', 'com1.js', 'aux', 'prn.css',
    'index.html.', 'index.html ', 'a'#0'b', 'assets/', '/',
    '%2e%2e/x', 'index%2ehtml', 'a%b',
    'com'#$C2#$B9'.js', // COM + superscript one device variant
    'CONIN$', 'conout$.css', // console devices
    'CON .txt', // device with space-padded base
    'a'#$7F'b'); // DEL control byte
  GOOD: array[0..5] of RawUtf8 = (
    'index.html', 'assets/app.js', 'assets/nested/deep/file.woff2',
    'a', 'com10.js', 'CamelCase.HTML');
var
  i: PtrInt;
  decoded, logical, long: RawUtf8;
begin
  for i := 0 to High(BAD) do
    CheckUtf8(not PWebAssetPathValid(BAD[i]), 'accepted: %', [BAD[i]]);
  for i := 0 to High(GOOD) do
    CheckUtf8(PWebAssetPathValid(GOOD[i]), 'rejected: %', [GOOD[i]]);
  // invalid and overlong (non-shortest-form) UTF-8
  Check(not PWebAssetPathValid('a'#$C0#$AF'b'), 'overlong slash');
  Check(not PWebAssetPathValid('a'#$E0#$80#$AF), 'overlong 3-byte');
  Check(not PWebAssetPathValid('a'#$ED#$A0#$80), 'surrogate half');
  Check(not PWebAssetPathValid('a'#$FF), 'invalid lead byte');
  Check(not PWebAssetPathValid('a'#$C3), 'truncated sequence');
  Check(not PWebAssetPathValid('a'#$C2#$85'b'), 'C1 control accepted');
  Check(PWebAssetPathValid('caf'#$C3#$A9'.txt'), 'valid utf-8 rejected');
  // length ceilings: segment max 255 bytes, path max 2048 bytes
  SetLength(long, PWEB_ASSET_SEGMENT_MAX_BYTES);
  FillChar(long[1], Length(long), Ord('a'));
  Check(PWebAssetPathValid(long), '255-byte segment rejected');
  Check(not PWebAssetPathValid(long + 'a'), '256-byte segment accepted');
  long := long + '/' + long + '/' + long + '/' + long; // 1023 bytes
  Check(PWebAssetPathValid(long + '/' + long), '2047-byte path rejected');
  Check(not PWebAssetPathValid(long + '/' + long + '/' + long),
    'over-limit path accepted');
  // deterministic MIME table
  CheckEqual(PWebAssetMimeType('a.html'), 'text/html; charset=utf-8');
  CheckEqual(PWebAssetMimeType('a.htm'), 'text/html; charset=utf-8');
  CheckEqual(PWebAssetMimeType('a.js'), 'text/javascript; charset=utf-8');
  CheckEqual(PWebAssetMimeType('a.mjs'), 'text/javascript; charset=utf-8');
  CheckEqual(PWebAssetMimeType('a.css'), 'text/css; charset=utf-8');
  CheckEqual(PWebAssetMimeType('a.json'), 'application/json; charset=utf-8');
  CheckEqual(PWebAssetMimeType('a.txt'), 'text/plain; charset=utf-8');
  CheckEqual(PWebAssetMimeType('a.svg'), 'image/svg+xml');
  CheckEqual(PWebAssetMimeType('a.png'), 'image/png');
  CheckEqual(PWebAssetMimeType('a.jpg'), 'image/jpeg');
  CheckEqual(PWebAssetMimeType('a.jpeg'), 'image/jpeg');
  CheckEqual(PWebAssetMimeType('a.gif'), 'image/gif');
  CheckEqual(PWebAssetMimeType('a.webp'), 'image/webp');
  CheckEqual(PWebAssetMimeType('a.ico'), 'image/x-icon');
  CheckEqual(PWebAssetMimeType('a.woff'), 'font/woff');
  CheckEqual(PWebAssetMimeType('a.woff2'), 'font/woff2');
  CheckEqual(PWebAssetMimeType('a.wasm'), 'application/wasm');
  CheckEqual(PWebAssetMimeType('a.HTML'), 'text/html; charset=utf-8');
  CheckEqual(PWebAssetMimeType('a.unknown'), PWEB_ASSET_FALLBACK_MIME);
  CheckEqual(PWebAssetMimeType('noext'), PWEB_ASSET_FALLBACK_MIME);
  CheckEqual(PWebAssetMimeType('dir.v1/noext'), PWEB_ASSET_FALLBACK_MIME);
  // strict single percent-decode
  Check(PWebPercentDecodeOnce('a%20b', decoded) and (decoded = 'a b'));
  Check(PWebPercentDecodeOnce('plain', decoded) and (decoded = 'plain'));
  Check(PWebPercentDecodeOnce('%2e', decoded) and (decoded = '.'));
  Check(not PWebPercentDecodeOnce('a%zz', decoded), 'bad hex accepted');
  Check(not PWebPercentDecodeOnce('a%2', decoded), 'truncated accepted');
  Check(not PWebPercentDecodeOnce('%', decoded), 'lone % accepted');
  // pweb://app URI translation - decode exactly once, then validate
  Check(PWebParseAppUri('pweb://app/', logical) and
    (logical = PWEB_ASSET_DEFAULT_DOCUMENT), 'root mapping');
  Check(PWebParseAppUri('pweb://app', logical) and
    (logical = PWEB_ASSET_DEFAULT_DOCUMENT), 'bare authority mapping');
  Check(PWebParseAppUri('pweb://app/index.html', logical) and
    (logical = 'index.html'));
  Check(PWebParseAppUri('pweb://app/assets/app.js', logical) and
    (logical = 'assets/app.js'));
  Check(PWebParseAppUri('PWEB://APP/index.html', logical) and
    (logical = 'index.html'), 'scheme/authority are case-insensitive');
  Check(PWebParseAppUri('pweb://app/index.html?v=1', logical) and
    (logical = 'index.html'), 'query cut before decode');
  Check(PWebParseAppUri('pweb://app/a#b', logical) and
    (logical = 'a'), 'fragment cut before decode');
  Check(PWebParseAppUri('pweb://app/?x=1', logical) and
    (logical = PWEB_ASSET_DEFAULT_DOCUMENT));
  Check(PWebParseAppUri('pweb://app/a%20b.css', logical) and
    (logical = 'a b.css'), 'single decode applies');
  // ratified order is decode once THEN validate, so an encoded slash
  // aliases the plain separator - pinned so it cannot drift silently
  Check(PWebParseAppUri('pweb://app/assets%2Fapp.js', logical) and
    (logical = 'assets/app.js'), 'decoded %2F separator');
  Check(not PWebParseAppUri('pweb://app/%2e%2e%2Fx', logical),
    'encoded traversal via %2F survived');
  Check(not PWebParseAppUri('pweb://other-host/probe', logical),
    'wrong authority trusted');
  Check(not PWebParseAppUri('pweb://app:80/x', logical), 'port trusted');
  Check(not PWebParseAppUri('pweb://user@app/x', logical),
    'userinfo trusted');
  Check(not PWebParseAppUri('https://app/x', logical), 'wrong scheme');
  Check(not PWebParseAppUri('pweb:/app/x', logical), 'malformed scheme');
  Check(not PWebParseAppUri('', logical), 'empty URI');
  Check(not PWebParseAppUri('pweb://app/%2e%2e/x', logical),
    'encoded traversal');
  Check(not PWebParseAppUri('pweb://app/%252e%252e/x', logical),
    'double-encoded traversal survived the single decode');
  Check(not PWebParseAppUri('pweb://app/a%zz', logical),
    'malformed escape');
  Check(not PWebParseAppUri('pweb://app/a%2', logical),
    'truncated escape');
  Check(not PWebParseAppUri('pweb://app/a%00b', logical), 'encoded NUL');
  Check(not PWebParseAppUri('pweb://app//x', logical), 'empty segment');
  Check(not PWebParseAppUri('pweb://app/a\b', logical), 'backslash');
end;

procedure TTestAssetStores.CorpusParity;
var
  i: PtrInt;
  fromFolder, fromZip, fromZipFile: TAssetResponse;
  zipFromFile: IAssetStore;
  logical: RawUtf8;
begin
  zipFromFile := TZipAssetStore.Create(fZipFile);
  for i := 0 to High(CORPUS) do
  begin
    CheckUtf8(fFolder.TryRead(CORPUS[i].Name, fromFolder),
      'folder miss: %', [CORPUS[i].Name]);
    CheckUtf8(fZip.TryRead(CORPUS[i].Name, fromZip),
      'zip miss: %', [CORPUS[i].Name]);
    CheckUtf8(zipFromFile.TryRead(CORPUS[i].Name, fromZipFile),
      'file-backed zip miss: %', [CORPUS[i].Name]);
    Check(fromFolder.Content = CorpusContent(CORPUS[i].Name),
      'folder bytes differ from corpus');
    Check(fromFolder.Content = fromZip.Content,
      'folder/zip bytes differ');
    Check(fromZip.Content = fromZipFile.Content,
      'memory/file zip bytes differ');
    CheckEqual(fromFolder.ContentType, CORPUS[i].Mime);
    CheckEqual(fromZip.ContentType, CORPUS[i].Mime);
    CheckEqual(fromZipFile.ContentType, CORPUS[i].Mime);
  end;
  // zero-byte asset is served, not confused with a miss
  Check(fFolder.TryRead('assets/empty.bin', fromFolder) and
    (fromFolder.Content = ''), 'folder zero-byte');
  Check(fZip.TryRead('assets/empty.bin', fromZip) and
    (fromZip.Content = ''), 'zip zero-byte');
  // missing paths fail from both stores
  Check(not fFolder.TryRead('missing.html', fromFolder));
  Check(not fZip.TryRead('missing.html', fromZip));
  Check(not fFolder.TryRead('assets/missing.js', fromFolder));
  Check(not fZip.TryRead('assets/missing.js', fromZip));
  // the empty path stays fail-closed at store level
  Check(not fFolder.TryRead('', fromFolder), 'folder empty path');
  Check(not fZip.TryRead('', fromZip), 'zip empty path');
  // a directory is not an asset
  Check(not fFolder.TryRead('assets', fromFolder), 'folder dir read');
  Check(not fZip.TryRead('assets', fromZip), 'zip dir read');
  // a file used as a directory is not a path
  Check(not fFolder.TryRead('index.html/x', fromFolder));
  Check(not fZip.TryRead('index.html/x', fromZip));
  // URI layer to store integration over the shared translation
  Check(PWebParseAppUri('pweb://app/assets/app.js', logical));
  Check(fFolder.TryRead(logical, fromFolder) and
    (fromFolder.Content = CorpusContent('assets/app.js')));
  Check(PWebParseAppUri('pweb://app/', logical));
  Check(fZip.TryRead(logical, fromZip) and
    (fromZip.Content = CorpusContent('index.html')));
end;

procedure TTestAssetStores.HostilePathMatrix;
const
  HOSTILE: array[0..17] of RawUtf8 = (
    '../x', './x', 'assets/../x', 'assets//x', 'a\b', '/absolute',
    'C:/x', '//server/share', 'x.txt:ads', 'NUL', 'nul.txt',
    'index.html.', 'index.html ', 'a'#0'b', '%2e%2e/x',
    'index%2ehtml', 'assets/', 'assets\app.js');
var
  i: PtrInt;
  a: TAssetResponse;
begin
  for i := 0 to High(HOSTILE) do
  begin
    CheckUtf8(not fFolder.TryRead(HOSTILE[i], a),
      'folder served hostile: %', [HOSTILE[i]]);
    CheckUtf8(not fZip.TryRead(HOSTILE[i], a),
      'zip served hostile: %', [HOSTILE[i]]);
  end;
end;

procedure TTestAssetStores.ExactCaseSensitivity;
var
  a: TAssetResponse;
begin
  // stored lowercase, requested with case variants
  Check(fFolder.TryRead('assets/app.js', a), 'exact case folder');
  Check(fZip.TryRead('assets/app.js', a), 'exact case zip');
  Check(not fFolder.TryRead('assets/App.js', a),
    'Windows case-insensitivity leaked into the folder store');
  Check(not fZip.TryRead('assets/App.js', a), 'zip case folded');
  Check(not fFolder.TryRead('ASSETS/app.js', a), 'folder dir case');
  Check(not fZip.TryRead('ASSETS/app.js', a), 'zip dir case');
  Check(not fFolder.TryRead('Index.html', a), 'folder file case');
  Check(not fZip.TryRead('Index.html', a), 'zip file case');
  // stored mixed-case, exact spelling required
  Check(fFolder.TryRead('assets/CamelCase.js', a), 'camel folder');
  Check(fZip.TryRead('assets/CamelCase.js', a), 'camel zip');
  Check(not fFolder.TryRead('assets/camelcase.js', a),
    'folder camel folded');
  Check(not fZip.TryRead('assets/camelcase.js', a), 'zip camel folded');
  {$ifdef OSWINDOWS}
  // 8.3 short-name aliasing must not resolve either: obtain the
  // volume's alias for a long-named corpus file and require a miss
  // (silently satisfied where the volume has 8.3 generation disabled)
  CheckShortNameAlias;
  {$endif OSWINDOWS}
end;

{$ifdef OSWINDOWS}
procedure TTestAssetStores.CheckShortNameAlias;
var
  longW, rootW: UnicodeString;
  buf: array[0..2047] of WideChar;
  len: DWORD;
  shortFull, alias: RawUtf8;
  i: PtrInt;
  a: TAssetResponse;
begin
  rootW := UnicodeString(Utf8ToSynUnicode(StringToUtf8(fRoot)));
  longW := rootW + '\assets\CamelCase.js';
  len := GetShortPathNameW(PWideChar(longW), @buf[0], Length(buf));
  if (len = 0) or
     (len >= DWORD(Length(buf))) then
  begin
    Check(True, '8.3 generation unavailable');
    exit;
  end;
  shortFull := RawUnicodeToUtf8(@buf[0], len);
  // relative alias below the root, with forward slashes
  alias := Copy(shortFull, Length(SynUnicodeToUtf8(rootW)) + 2, MaxInt);
  for i := 1 to Length(alias) do
    if alias[i] = '\' then
      alias[i] := '/';
  if alias = 'assets/CamelCase.js' then
  begin
    Check(True, 'volume produced no distinct 8.3 alias');
    exit;
  end;
  CheckUtf8(not fFolder.TryRead(alias, a),
    '8.3 alias resolved in the folder store: %', [alias]);
end;
{$endif OSWINDOWS}

procedure TTestAssetStores.NonAsciiNames;
const
  NAME: RawUtf8 = 'assets/caf'#$C3#$A9'.bin'; // cafe with e-acute
var
  full: TFileName;
  a: TAssetResponse;
  store: IAssetStore;
begin
  // folder store: UTF-8 logical name resolved over the UTF-16 walk
  full := fRoot + PathDelim + 'assets' + PathDelim +
    Utf8ToString(RawUtf8('caf'#$C3#$A9'.bin'));
  Check(FileFromString('utf8-content', full), 'cannot write utf8 fixture');
  Check(fFolder.TryRead(NAME, a) and
    (a.Content = 'utf8-content'), 'folder utf8 name miss');
  CheckEqual(a.ContentType, PWEB_ASSET_FALLBACK_MIME);
  // exact case holds beyond ASCII: E-ACUTE must not resolve e-acute
  Check(not fFolder.TryRead('assets/caf'#$C3#$89'.bin', a),
    'folder folded non-ascii case');
  // zip store: the raw stored-name bytes are the same UTF-8
  store := TZipAssetStore.CreateFromBuffer(
    BuildRawZip([RawByteString(NAME)]));
  Check(store.TryRead(NAME, a) and
    (a.Content = ''), 'zip utf8 name miss');
  Check(not store.TryRead('assets/caf'#$C3#$89'.bin', a),
    'zip folded non-ascii case');
  store := nil;
end;

procedure TTestAssetStores.HostileArchives;

  procedure CheckRejected(const Names: array of RawByteString;
    const What: RawUtf8);
  var
    store: IAssetStore;
    rejected: Boolean;
  begin
    rejected := False;
    try
      store := TZipAssetStore.CreateFromBuffer(BuildRawZip(Names));
      store := nil;
    except
      on EPWebZipAssetStore do
        rejected := True;
    end;
    CheckUtf8(rejected, 'hostile archive accepted: %', [What]);
  end;

var
  store: IAssetStore;
  a: TAssetResponse;
  rejected: Boolean;
begin
  // control: a canonical raw archive is accepted
  store := TZipAssetStore.CreateFromBuffer(
    BuildRawZip(['ok.css', 'assets/ok.js']));
  Check(store.TryRead('ok.css', a) and (a.Content = ''),
    'valid raw archive refused');
  store := nil;
  // ambiguous or hostile entries reject the whole archive
  CheckRejected(['a.js', 'a.js'], 'duplicate names');
  CheckRejected(['assets/app.js', 'assets/App.js'], 'case collision');
  CheckRejected(['assets\app.js'], 'backslash name');
  CheckRejected(['../evil.js'], 'traversal name');
  CheckRejected(['assets/../evil.js'], 'inner traversal name');
  CheckRejected(['/etc/passwd'], 'absolute-like name');
  CheckRejected(['C:/evil.js'], 'drive-prefixed name');
  CheckRejected(['assets/'], 'folder entry');
  CheckRejected(['nul.txt'], 'device name');
  CheckRejected(['a%2e.js'], 'percent in stored name');
  CheckRejected(['bad'#0'name.js'], 'embedded NUL');
  CheckRejected(['trailing.js '], 'trailing space');
  // a name that is also a directory prefix of another cannot exist in
  // any folder store - parity would be silently unenforceable
  CheckRejected(['a', 'a/b.js'], 'file/directory collision');
  CheckRejected(['assets/app.js', 'assets/app.js/x'], 'file used as dir');
  // a parseable archive with no entries is a broken package
  CheckRejected([], 'empty archive');
  // an entry claiming more than the 2GB materialisation bound
  rejected := False;
  try
    store := TZipAssetStore.CreateFromBuffer(
      BuildRawZipSizedEntry('huge.bin', $80000000));
    store := nil;
  except
    on EPWebZipAssetStore do
      rejected := True;
  end;
  Check(rejected, 'oversized entry accepted');
  // control for the size crafting itself: a modest declared size is
  // accepted through the same raw path
  store := TZipAssetStore.CreateFromBuffer(
    BuildRawZipSizedEntry('claim.bin', 0));
  Check(store <> nil, 'sized-entry control refused');
  store := nil;
  // not a ZIP at all
  try
    store := TZipAssetStore.CreateFromBuffer('this is not a zip');
    Check(False, 'garbage archive accepted');
    store := nil;
  except
    on EPWebZipAssetStore do
      Check(True);
  end;
end;

procedure TTestAssetStores.ConstructorFailures;

  procedure CheckFolderRefused(const Root: TFileName; const What: RawUtf8);
  var
    store: IAssetStore;
    refused: Boolean;
  begin
    refused := False;
    try
      store := TFolderAssetStore.Create(Root);
      store := nil;
    except
      on EPWebFolderAssetStore do
        refused := True;
    end;
    CheckUtf8(refused, 'folder root accepted: %', [What]);
  end;

var
  store: IAssetStore;
  refused: Boolean;
begin
  CheckFolderRefused('', 'empty root');
  CheckFolderRefused(fRoot + PathDelim + 'no-such-dir', 'missing root');
  CheckFolderRefused(fZipFile, 'file as root');
  refused := False;
  try
    store := TZipAssetStore.Create(fZipFile + '.missing');
    store := nil;
  except
    on EPWebZipAssetStore do
      refused := True;
  end;
  Check(refused, 'missing archive file accepted');
end;

procedure TTestAssetStores.RootConfinement;
var
  a: TAssetResponse;
begin
  {$ifdef OSWINDOWS}
  Check(fJunction <> '', 'junction fixture could not be created');
  {$endif OSWINDOWS}
  if fJunction = '' then
    exit; // non-Windows or non-NTFS temp: fixture not expressible
  // the file exists and is readable through the filesystem...
  Check(FileExists(fJunction + PathDelim + 'secret.bin'),
    'junction fixture is not functional');
  // ...but the store never follows the reparse point
  Check(not fFolder.TryRead('outlink/secret.bin', a),
    'folder store escaped its root through a junction');
  Check(not fFolder.TryRead('outlink', a), 'junction served as asset');
  // control: confined reads still work
  Check(fFolder.TryRead('index.html', a), 'confined read broken');
end;

type
  TReaderThreadContext = record
    Store: IAssetStore;
    Failures: LongInt;
    Loops: Integer;
  end;
  PReaderThreadContext = ^TReaderThreadContext;

function ReaderThread(Param: Pointer): PtrInt;
var
  ctx: PReaderThreadContext;
  i, c: PtrInt;
  a: TAssetResponse;
  name: RawUtf8;
begin
  Result := 0;
  ctx := Param;
  for i := 1 to ctx^.Loops do
  begin
    c := i mod (High(CORPUS) + 1);
    name := CORPUS[c].Name;
    if not ctx^.Store.TryRead(name, a) or
       (a.Content <> CorpusContent(name)) or
       (a.ContentType <> CORPUS[c].Mime) then
      InterlockedIncrement(ctx^.Failures);
    if ctx^.Store.TryRead('missing-' + name, a) then
      InterlockedIncrement(ctx^.Failures);
  end;
end;

procedure TTestAssetStores.RepeatedAndConcurrentReads;
const
  THREADS = 6;
  LOOPS = 250;
var
  i, t: PtrInt;
  a, b: TAssetResponse;
  ctx: array[0..THREADS - 1] of TReaderThreadContext;
  handles: array[0..THREADS - 1] of system.TThreadID;
  ids: system.TThreadID;
begin
  // repeated sequential reads are stable
  for i := 1 to 100 do
  begin
    Check(fFolder.TryRead('assets/nested/data.bin', a));
    Check(fZip.TryRead('assets/nested/data.bin', b));
    Check(a.Content = b.Content, 'repeated read diverged');
  end;
  // concurrent reads over both stores stay deterministic
  for t := 0 to THREADS - 1 do
  begin
    if Odd(t) then
      ctx[t].Store := fZip
    else
      ctx[t].Store := fFolder;
    ctx[t].Failures := 0;
    ctx[t].Loops := LOOPS;
    handles[t] := BeginThread(@ReaderThread, @ctx[t], ids);
    Check(handles[t] <> system.TThreadID(0), 'thread start failed');
  end;
  for t := 0 to THREADS - 1 do
  begin
    Check(WaitForThreadTerminate(handles[t], 30000) = 0,
      'reader thread hung');
    CloseThread(handles[t]);
  end;
  for t := 0 to THREADS - 1 do
    CheckEqual(ctx[t].Failures, 0, 'concurrent reads diverged');
end;

type
  TBigZipThreadContext = record
    Store: IAssetStore;
    Big, Small: RawByteString;
    Failures: LongInt;
    Loops: Integer;
  end;
  PBigZipThreadContext = ^TBigZipThreadContext;

function BigZipReader(Param: Pointer): PtrInt;
var
  ctx: PBigZipThreadContext;
  i: PtrInt;
  a: TAssetResponse;
begin
  Result := 0;
  ctx := Param;
  for i := 1 to ctx^.Loops do
  begin
    if not ctx^.Store.TryRead('big.bin', a) or
       (a.Content <> ctx^.Big) then
      InterlockedIncrement(ctx^.Failures);
    if not ctx^.Store.TryRead('small.js', a) or
       (a.Content <> ctx^.Small) then
      InterlockedIncrement(ctx^.Failures);
    if ctx^.Store.TryRead('missing.bin', a) then
      InterlockedIncrement(ctx^.Failures);
  end;
end;

procedure TTestAssetStores.FileBackedArchiveConcurrency;
const
  THREADS = 4;
  LOOPS = 15;
var
  big, small, bytes: RawByteString;
  seed: Cardinal;
  i, t: PtrInt;
  mem: TMemoryStream;
  zw: TZipWrite;
  zfile: TFileName;
  store: IAssetStore;
  a: TAssetResponse;
  ctx: array[0..THREADS - 1] of TBigZipThreadContext;
  handles: array[0..THREADS - 1] of system.TThreadID;
  ids: system.TThreadID;
begin
  // an entry larger than TZipRead's 1MB working memory forces the
  // shared seekable fSource path inside UnZip - the exact code the
  // store's private lock serializes; incompressible pseudo-random
  // bytes keep the deflated stream past the window too
  SetLength(big, (1 shl 20) + 65536);
  seed := $2A2A2A2A;
  for i := 1 to Length(big) do
  begin
    seed := seed xor (seed shl 13);
    seed := seed xor (seed shr 17);
    seed := seed xor (seed shl 5);
    big[i] := AnsiChar(seed and 255);
  end;
  small := 'console.log("big archive");';
  mem := TMemoryStream.Create;
  try
    zw := TZipWrite.Create(mem);
    try
      zw.AddDeflated('big.bin', pointer(big), Length(big));
      zw.AddDeflated('small.js', pointer(small), Length(small));
    finally
      zw.Free;
    end;
    SetString(bytes, PAnsiChar(mem.Memory), mem.Size);
  finally
    mem.Free;
  end;
  zfile := GetTempDir + 'pweb-cap4-' + IntToStr(GetCurrentProcessId) +
    PathDelim + 'big.zip';
  Check(FileFromString(bytes, zfile), 'cannot write big fixture archive');
  store := TZipAssetStore.Create(zfile);
  Check(store.TryRead('big.bin', a) and
    (a.Content = big), 'file-backed big entry read');
  Check(store.TryRead('small.js', a) and
    (a.Content = small), 'file-backed small entry read');
  for t := 0 to THREADS - 1 do
  begin
    ctx[t].Store := store;
    ctx[t].Big := big;
    ctx[t].Small := small;
    ctx[t].Failures := 0;
    ctx[t].Loops := LOOPS;
    handles[t] := BeginThread(@BigZipReader, @ctx[t], ids);
    Check(handles[t] <> system.TThreadID(0), 'thread start failed');
  end;
  for t := 0 to THREADS - 1 do
  begin
    Check(WaitForThreadTerminate(handles[t], 60000) = 0,
      'file-backed reader thread hung');
    CloseThread(handles[t]);
  end;
  for t := 0 to THREADS - 1 do
    CheckEqual(ctx[t].Failures, 0, 'file-backed concurrent reads diverged');
  store := nil;
end;

end.
