{
  pweb.cli.template - CAP-10B0 trusted template distribution: the build-time
  list, the deterministic pack writer, the generated native registry and the
  runtime pack verifier.

  DELIBERATELY PLATFORM-FREE. Nothing here names an operating system and
  nothing here carries a conditional: the CAP-7F sweep holds this unit at
  zero. It touches the filesystem in exactly one direction and for exactly
  one caller - the BUILD-TIME pack writer, which produces an artifact under
  build/ and commits it through the one replacing primitive in
  pweb.cli.platform. The RUNTIME half reads nothing: it is handed bytes that
  were already read once, and answers about them.

  ---------------------------------------------------------------------------
  WHAT IS AUTHORITATIVE: THE GENERATED REGISTRY, AND NOTHING ELSE
  ---------------------------------------------------------------------------

  The archive carries BYTES. It carries nothing else, and it is believed
  about nothing else. Every name, every output path, every content kind,
  every file mode, every byte length, every digest and the set of template
  ids themselves are COMPILED CONSTANTS emitted by the trusted build.

  So a substituted or tampered pack cannot:

    - redirect an output path (the mapping is not in the archive);
    - mark a generated file executable (the mode is not in the archive -
      and could not be, because the deterministic writer zeroes the ZIP
      external attributes; see the DETERMINISM note below);
    - reclassify a binary as text and so become subject to substitution;
    - add a file, remove a file or rename one (the inventory is compared
      entry by entry, and the entry COUNT is compared too);
    - redefine its own expected hash;
    - offer a template id the CLI does not already know;
    - make a PRIVATE template reachable from a public command.

  That is the whole security argument, and it is why the registry is
  generated by the build rather than read from the artifact it describes.

  ---------------------------------------------------------------------------
  DETERMINISM - AND WHY THIS ARCHIVE IS STORED, NOT DEFLATED
  ---------------------------------------------------------------------------

  CAP-6/CAP-7L MEASURED that mORMot's static DEFLATE object emits different
  bytes for x86_64-win64 and x86_64-linux, which is why app.pwb's golden
  hash is pinned per toolchain and why plugins.zip generates its registry
  per target.

  This pack takes the other road: every entry is STORED, so no compressor is
  reached at all. What remains in the file is a function of the entry names,
  their bytes, their CRC-32s, a fixed timestamp - TZipWrite zeroes the whole
  entry record before filling it and writes no extra field - and ONE BYTE
  PER ENTRY that records the operating system which created the archive.

  That last byte is worth stating plainly, because the first version of this
  header claimed it did not exist. mORMot writes the creating OS into the
  ZIP `version made by` field: ZIP_OS is 19 on Darwin and 3 everywhere else.
  A dev-host measurement across the i386-win32 and x86_64-win64 toolchains
  produced byte-identical archives and was read as proving OS-independence -
  it could not, because both are Windows. The four-target matrix measured
  the truth on hosted run 33093385300: one hash for windows + linux, another
  for the two macOS targets, with the SAME length and the SAME semantic
  inventory, and with macos-x86_64 and macos-arm64 agreeing exactly.

  So the archive is deterministic PER OS FAMILY, and the evidence splits
  accordingly: the semantic inventory is compared across all four targets,
  the pack SHA-256 is pinned per target, and the gate rebuilds the pack on
  each target and requires byte equality there. That is the same split
  CAP-9C1 applies to plugins.zip, reached by measurement rather than
  inherited by assumption.

  The consequence for file modes is unchanged, and is the useful half:
  because the external attributes are zero, the archive is STRUCTURALLY
  incapable of carrying a POSIX mode whatever OS wrote it. The file-mode
  question therefore has exactly one answer - the registry - and there is no
  second one for it to disagree with.

  ---------------------------------------------------------------------------
  THE ORDER THE VERIFIER RUNS IN, AND WHY IT IS THAT ORDER
  ---------------------------------------------------------------------------

    registry self-consistency        (before ANY byte is believed)
        -> the pack bytes, read ONCE by the caller while hashing
        -> exact byte length, then exact SHA-256
        -> TZipAssetStore over THOSE SAME BYTES
        -> the entry count, then the semantic inventory entry by entry
        -> only then does a store escape

  There is no check-then-open window to race, because there is no second
  read: the bytes that were hashed are the bytes that are parsed. That is
  the ratified CAP-9C1 shape, reused rather than re-argued.

  Canonical sources:
    - core-interfaces.md : IAssetStore.TryRead (frozen) + the canonical
                           asset-path rules, reused verbatim.
    - security-model.md  : the native trust anchor; packaged content grants
                           nothing.
}
unit pweb.cli.template;

{$mode ObjFPC}{$H+}

interface

uses
  sysutils,
  mormot.core.base,
  mormot.core.os,
  mormot.core.unicode,
  mormot.core.zip,
  mormot.crypt.core,
  pweb.assets.intf,
  pweb.assets.support,
  pweb.assets.zip,
  pweb.assets.bundle,   // the ratified deterministic-ZIP constants
  pweb.cli.platform;    // the ONE replacing primitive, for the build writer

const
  /// the template-pack contract version. A change of MEANING is a bump,
  // never a new optional field - the same growth rule schema 1 of
  // pweb.json follows, for the same reason
  PWEB_TPL_SCHEMA = 1;

  /// the generated native registry include. Written into the staging
  // directory and compiled with -Fi; NEVER a runtime configuration file
  PWEB_TPL_REGISTRY_INC = 'pweb.templates.registry.inc';

  { ---- the bounds. Private CLI implementation limits: not protocol
    fields, not descriptor fields, and not raisable from the archive ---- }

  /// hard ceiling on the whole pack. Checked against the size the OS
  // reports BEFORE a byte is read, because the verifier materialises the
  // archive to close the check/open race and this is what bounds that cost
  PWEB_TPL_PACK_MAX_BYTES = Int64(8) shl 20;        // 8 MiB
  /// hard ceiling on one packed template file
  PWEB_TPL_FILE_MAX_BYTES = Int64(1) shl 20;        // 1 MiB
  /// hard ceiling on everything one created project may weigh
  PWEB_TPL_TOTAL_MAX_BYTES = Int64(16) shl 20;      // 16 MiB
  /// hard ceiling on archive entries
  PWEB_TPL_MAX_ENTRIES = 512;
  /// hard ceiling on templates in one pack
  PWEB_TPL_MAX_TEMPLATES = 8;
  /// hard ceiling on files in one created project
  PWEB_TPL_MAX_OUTPUT_FILES = 256;
  /// hard ceiling on a rendered project-relative path, in bytes. Well
  // under a legacy 260-character MAX_PATH so a generated project stays
  // openable by tools this CLI does not control
  PWEB_TPL_PATH_MAX_BYTES = 240;
  /// hard ceiling on one path segment, in bytes
  PWEB_TPL_SEGMENT_MAX_BYTES = 128;
  /// hard ceiling on any substituted placeholder VALUE, in bytes
  PWEB_TPL_TOKEN_MAX_BYTES = 128;
  /// hard ceiling on the trusted build-time list, in bytes
  PWEB_TPL_LIST_MAX_BYTES = 64 shl 10;              // 64 KiB
  /// hard ceiling on a template identifier, in bytes
  PWEB_TPL_ID_MAX_BYTES = 32;

  /// the ZIP compression method for a stored entry, as the .ZIP appnote
  // defines it. Declared here rather than imported so this unit does not
  // pull a compression library header in merely to name the absence of
  // compression
  PWEB_TPL_ZIP_STORED = 0;

type
  /// direct misuse of the build-time API - never raised by the runtime
  // verifier, which returns typed codes instead
  EPWebTemplate = class(Exception);

  { Why a template-pack operation failed. NATIVE build/verify codes:
    deliberately NOT the nine-code RPC taxonomy (wire-semantics.md) -
    nothing here is an invocation - and deliberately not the scaffold codes
    either, because "this pack is not trustworthy" and "this project cannot
    be created here" are different failures with different fixes. }
  TPWebTplCode = (
    ptcNone,
    // ---- the trusted build-time list ----
    ptcListTooLarge,
    ptcListEncoding,          // NUL, non-ASCII or a control byte
    ptcListSyntax,
    ptcListSchema,
    ptcListDuplicateKey,
    ptcListUnknownField,
    ptcListMissingField,
    ptcListTemplateId,
    ptcListDuplicate,         // duplicate template id, source or output
    ptcListSource,
    ptcListOutput,
    ptcListContent,
    ptcListMode,
    ptcListUi,
    ptcListVisibility,
    ptcListLayout,            // a native/frontend/output layout value
    ptcListEmpty,
    ptcListCount,
    // ---- deterministic packaging ----
    ptcEntryName,             // not a canonical logical path
    ptcEntryOutsideRoot,      // not under its own template's root
    ptcEntryDuplicate,
    ptcEntryCollision,        // Unicode fold or file/directory collision
    ptcEntryCodepage,         // not byte-representable through TZipWrite
    ptcEntryTooLarge,
    ptcEntryCount,
    ptcEntryEncoding,         // a text template that is not strict UTF-8
    ptcEntryLineEnding,       // a CR byte, or a missing final newline
    ptcEntrySecret,           // a secret or build artifact in the source
    ptcEntryHostPath,         // an absolute host path baked into a template
    ptcArchiveWrite,          // the writer or its self-validation failed
    // ---- the generated native registry ----
    ptcRegistry,              // the registry itself is inconsistent
    ptcRegistryEmit,          // a field is not safely emittable as Pascal
    // ---- runtime whole-pack verification ----
    ptcPackSize,              // short, long or over the hard cap
    ptcPackDigest,            // the whole-archive SHA-256 does not match
    ptcArchiveInvalid,        // TZipAssetStore refused the archive
    ptcInventoryCount,
    ptcInventoryMismatch,
    ptcTemplateUnknown,       // no such template id in this registry
    ptcTemplatePrivate);      // a private template asked for publicly

  /// how one packed file's bytes become one generated file's bytes
  TPWebTplContent = (
    /// strict UTF-8, LF-only, placeholders expanded
    ptkText,
    /// copied byte-identically; NEVER substituted
    ptkBinary);

  /// the whole file-mode vocabulary. Two values, allowlisted: an archive
  // cannot carry a mode at all (see the unit header) and arbitrary host
  // permissions are never preserved
  TPWebTplMode = (
    ptmNormal,
    ptmExecutable);

  { ONE semantic inventory row. The inventory is what the archive MEANS -
    logical name, exact uncompressed length, exact content digest. Unlike
    the archive bytes it is toolchain- AND OS-independent by construction,
    which is why it and not the pack hash is the four-target equality
    field (see the DETERMINISM note in the unit header). }
  TPWebTplInventoryEntry = record
    Name: RawUtf8;
    Bytes: Int64;
    Sha256: RawUtf8;   // 64 lowercase hex
  end;
  TPWebTplInventory = array of TPWebTplInventoryEntry;

  { ONE registry file row: everything about one generated file EXCEPT its
    bytes. OutPath may carry placeholders; Archive never does. }
  TPWebTplFile = record
    Archive: RawUtf8;          // '<template-id>/<source>'
    OutPath: RawUtf8;          // project-relative output path template
    Content: TPWebTplContent;
    Mode: TPWebTplMode;
    Bytes: Int64;
    Sha256: RawUtf8;
  end;
  TPWebTplFiles = array of TPWebTplFile;

  { ONE registered template. The file rows are a SLICE of the registry's
    flat Files array rather than a nested dynamic array, because a typed
    Pascal constant - which is what the generated include emits, under
    WRITEABLECONST OFF - cannot express a nested one. }
  TPWebTplTemplate = record
    Id: RawUtf8;
    /// False keeps the template unreachable from any public command even
    // when it is present in the pack. The CAP-10B0 fixture is private
    IsPublic: Boolean;
    Ui: RawUtf8;               // 'react' | 'pas2js'
    NativeDir: RawUtf8;        // 'src'      -> native.program directory
    NativeExt: RawUtf8;        // 'lpr'      -> native.program extension
    FrontendRoot: RawUtf8;     // 'frontend' -> frontend.root
    OutputDir: RawUtf8;        // 'dist'     -> output
    FirstFile: Integer;
    FileCount: Integer;
  end;
  TPWebTplTemplates = array of TPWebTplTemplate;

  { The whole generated registry. THIS RECORD IS THE TRUST ANCHOR. It is
    passed as a PARAMETER rather than read from a global, so every refusal
    branch can be proven red on a mutated copy without regenerating an
    include - and so nothing can ever accidentally consult a second, softer
    registry from somewhere else. }
  TPWebTemplateRegistry = record
    Schema: Integer;
    PackFile: RawUtf8;         // a bare file name, no directory part
    PackSha256: RawUtf8;
    PackBytes: Int64;
    InventoryDigest: RawUtf8;
    Inventory: TPWebTplInventory;   // sorted bytewise by Name
    Files: TPWebTplFiles;           // grouped by template, sorted by Archive
    Templates: TPWebTplTemplates;   // sorted bytewise by Id
  end;

  { ONE row of the trusted build-time list, before anything is hashed.
    Build-time only: never shipped, never read at runtime. HasContent and
    HasMode exist so an OMITTED classification is a refusal rather than a
    silent default - the whole point of declaring every file explicitly. }
  TPWebTrustedFile = record
    Template: RawUtf8;
    Source: RawUtf8;           // template-root-relative, forward slashes
    OutPath: RawUtf8;
    Content: TPWebTplContent;
    Mode: TPWebTplMode;
    HasContent: Boolean;
    HasMode: Boolean;
  end;
  TPWebTrustedFiles = array of TPWebTrustedFile;

  TPWebTrustedTemplate = record
    Id: RawUtf8;
    IsPublic: Boolean;
    Ui: RawUtf8;
    NativeDir: RawUtf8;
    NativeExt: RawUtf8;
    FrontendRoot: RawUtf8;
    OutputDir: RawUtf8;
  end;
  TPWebTrustedTemplates = array of TPWebTrustedTemplate;

  { ONE entry handed to the deterministic writer. }
  TPWebTplEntry = record
    Name: RawUtf8;
    Content: RawByteString;
  end;
  TPWebTplEntries = array of TPWebTplEntry;

/// fixed diagnostic text for a code - the machine authority, never prose
function PWebTplCodeText(Code: TPWebTplCode): RawUtf8;

/// 'text' | 'binary'
function PWebTplContentText(Kind: TPWebTplContent): RawUtf8;
/// exact reverse of PWebTplContentText; False on anything else
function PWebTplContentOf(const S: RawUtf8;
  out Kind: TPWebTplContent): Boolean;
/// 'normal' | 'executable'
function PWebTplModeText(Mode: TPWebTplMode): RawUtf8;
/// exact reverse of PWebTplModeText; False on anything else
function PWebTplModeOf(const S: RawUtf8; out Mode: TPWebTplMode): Boolean;

/// template identifier grammar: ^[a-z][a-z0-9]*(-[a-z0-9]+)*$, bounded
function PWebTplIdValid(const Id: RawUtf8): Boolean;

/// ONE lower-case alphanumeric path segment ('src', 'frontend', 'dist',
/// 'lpr') - never a path, so a layout value can introduce no directory
/// level nobody reviewed
function PWebTplLayoutValid(const S: RawUtf8): Boolean;

/// a template-root-relative source or output path
// - the shared canonical-logical-path grammar (PWebAssetPathValid: no
// absolute form, no drive/UNC, no backslash, no '.'/'..'/empty segment, no
// NUL or control byte, no '%', no Windows device name, no trailing dot or
// space, strict shortest-form UTF-8) PLUS this layer's tighter bounds
// - Placeholders allows the {{TOKEN}} form; a source path never carries
// one and an output path may
function PWebTplPathValid(const Path: RawUtf8;
  Placeholders: Boolean): Boolean;

/// how many '/'-separated segments a path has
// - the structural half of the separator-injection refusal: a rendered
// path must have exactly as many segments as the template it came from
function PWebTplSegmentCount(const Path: RawUtf8): Integer;

/// True iff S is exactly 64 lowercase hexadecimal digits
function PWebTplSha256HexValid(const S: RawUtf8): Boolean;
/// lowercase hexadecimal SHA-256 of a byte string
function PWebTplSha256Hex(const Data: RawByteString): RawUtf8;

/// is this OUTPUT path a secret, a credential or a build artifact
// - by path and name ONLY; no content is ever read to classify
// - dot-files are an ALLOWLIST ('.gitignore', '.gitattributes',
// '.editorconfig') rather than a deny-list, because the interesting
// mistakes in this class are exactly the ones nobody thought to forbid
function PWebTplSecretOutput(const Path: RawUtf8): Boolean;

/// does this byte string carry an absolute host path or a home/user
// reference that must never be baked into a generated project
function PWebTplHasHostPath(const Data: RawByteString): Boolean;

/// strict text rules for a packed text template: no NUL, no BOM, strict
// shortest-form UTF-8, no CR anywhere, exactly one terminating LF
function PWebTplTextValid(const Data: RawByteString;
  out Code: TPWebTplCode): Boolean;

/// the canonical semantic-inventory projection: one LF-terminated
// 'name bytes sha' line per entry, in the inventory's own order
function PWebTplInventoryText(const Inv: TPWebTplInventory): RawUtf8;
/// SHA-256 of PWebTplInventoryText - the toolchain- and OS-independent
// identity of what the pack MEANS, as opposed to what it weighs
function PWebTplInventoryDigest(const Inv: TPWebTplInventory): RawUtf8;

/// the canonical projection of the WHOLE registry: schema, pack identity,
// every template row and every file row, one LF-terminated line each
// - this is a four-target equality field: two runners that disagree about
// any declared name, kind, mode or digest disagree here
function PWebTplRegistryText(const Reg: TPWebTemplateRegistry): RawUtf8;
/// SHA-256 of PWebTplRegistryText
function PWebTplRegistryDigest(const Reg: TPWebTemplateRegistry): RawUtf8;

/// strict scanner for the trusted build-time template list
// - the repository's existing `key = value` lock-file grammar: '#'
// comments, blank lines, `template = <id>` opening a block and
// `file = <source>` opening a file block inside it, each key at most once
// per block, ASCII only, no escape sequence anywhere, bounded
// - unknown keys are hard errors, and so is an OMITTED one
// - Detail is a short ASCII diagnostic ('' when none)
function PWebTplParseList(const Bytes: RawByteString;
  out Templates: TPWebTrustedTemplates; out Files: TPWebTrustedFiles;
  out Code: TPWebTplCode; out Detail: RawUtf8): Boolean;

/// deterministic validating template-pack writer (BUILD TIME ONLY)
// - validates every entry BEFORE touching the disk: canonical name,
// membership of a registered template root, exact duplicates, the ratified
// CAP-6 D1 Unicode-fold collision rule, file/directory collisions, the
// codepage round-trip and the size/count bounds
// - writes a temp sibling in global bytewise name order with every entry
// STORED and the CAP-6 fixed timestamp, re-opens it through TZipRead for a
// raw stored-name/method/timestamp/extra-field compare and through the
// PRODUCTION TZipAssetStore for a full content compare, then atomically
// replaces OutFile; on any failure the previous output survives and the
// temp is removed
function PWebTplWritePack(const OutFile: RawUtf8;
  const Entries: TPWebTplEntries; const Roots: TRawUtf8DynArray;
  out Inv: TPWebTplInventory; out PackSha256: RawUtf8; out PackBytes: Int64;
  out Code: TPWebTplCode; out Detail: RawUtf8): Boolean;

/// assemble a registry record from the generated include's constants
function PWebTplRegistryFrom(const PackFile, PackSha256: RawUtf8;
  PackBytes: Int64; const InventoryDigest: RawUtf8;
  const Inv: array of TPWebTplInventoryEntry;
  const Files: array of TPWebTplFile;
  const Templates: array of TPWebTplTemplate): TPWebTemplateRegistry;

/// internal-consistency gate over a registry, run before ANY byte of an
/// archive is believed: schema, grammars, digest shapes, sort order,
/// uniqueness, slice coherence, root membership, secret outputs, and the
/// exact agreement between the file rows and the inventory
function PWebTplValidateRegistry(const Reg: TPWebTemplateRegistry;
  out Code: TPWebTplCode; out Detail: RawUtf8): Boolean;

/// emit the deterministic generated native registry include
// - the registry is re-validated first, and every emitted string must be
// printable ASCII without a quote or a backslash, so NO arbitrary text can
// ever become Pascal source; a violation is a REFUSAL (ptcRegistryEmit),
// never an escape - escaping is how a generator becomes the place where
// arbitrary text turns into code
// - the output carries no absolute path, no timestamp and no host name, and
// is LF-terminated, so regeneration is byte-identical
function PWebTplEmitRegistry(const Reg: TPWebTemplateRegistry;
  const ToolId: RawUtf8; out Text: RawUtf8;
  out Code: TPWebTplCode; out Detail: RawUtf8): Boolean;

/// find a template by id
// - RequirePublic refuses a private template with its OWN code, so a
// public command can never reach one even by exact name
function PWebTplFind(const Reg: TPWebTemplateRegistry; const Id: RawUtf8;
  RequirePublic: Boolean; out Index: Integer;
  out Code: TPWebTplCode): Boolean;

/// read a template pack ONCE into memory and hash what was read
// - the size is bounded BEFORE a byte is read, from the size the OS
// reports, because the verifier materialises the archive to close the
// check/open race and this is what bounds that cost
// - the file is opened refusing reparse indirection and anything that is
// not a regular file, and the bytes returned are the ONLY bytes any caller
// ever sees: PWebTplVerifyPack parses these same bytes rather than
// re-opening the path, so there is no window between the two
function PWebTplLoadPack(const PackPath: RawUtf8; out Data: RawByteString;
  out PackSha256: RawUtf8; out Code: TPWebTplCode): Boolean;

/// THE pack verifier - the entry point every consumer uses
// - PackData are the bytes a caller already read ONCE while hashing them,
// and PackSha256 is that same read's digest. Nothing here re-reads a file,
// because a second read is a second set of bytes
// - on False Store is nil and no archive was ever handed to anything
function PWebTplVerifyPack(const Reg: TPWebTemplateRegistry;
  const PackData: RawByteString; const PackSha256: RawUtf8;
  out Store: IAssetStore; out Code: TPWebTplCode;
  out Detail: RawUtf8): Boolean;


implementation

const
  PWEB_TPL_CODE_TEXT: array[TPWebTplCode] of RawUtf8 = (
    'ok',
    'list_too_large',
    'list_encoding',
    'list_syntax',
    'list_schema',
    'list_duplicate_key',
    'list_unknown_field',
    'list_missing_field',
    'list_template_id',
    'list_duplicate',
    'list_source',
    'list_output',
    'list_content',
    'list_mode',
    'list_ui',
    'list_visibility',
    'list_layout',
    'list_empty',
    'list_count',
    'entry_name',
    'entry_outside_root',
    'entry_duplicate',
    'entry_collision',
    'entry_codepage',
    'entry_too_large',
    'entry_count',
    'entry_encoding',
    'entry_line_ending',
    'entry_secret',
    'entry_host_path',
    'archive_write',
    'registry',
    'registry_emit',
    'pack_size',
    'pack_digest',
    'archive_invalid',
    'inventory_count',
    'inventory_mismatch',
    'template_unknown',
    'template_private');

function PWebTplCodeText(Code: TPWebTplCode): RawUtf8;
begin
  Result := PWEB_TPL_CODE_TEXT[Code];
end;

function PWebTplContentText(Kind: TPWebTplContent): RawUtf8;
begin
  if Kind = ptkBinary then
    Result := 'binary'
  else
    Result := 'text';
end;

function PWebTplContentOf(const S: RawUtf8;
  out Kind: TPWebTplContent): Boolean;
begin
  Kind := ptkText;
  Result := True;
  if S = 'text' then
    exit;
  if S = 'binary' then
  begin
    Kind := ptkBinary;
    exit;
  end;
  Result := False;
end;

function PWebTplModeText(Mode: TPWebTplMode): RawUtf8;
begin
  if Mode = ptmExecutable then
    Result := 'executable'
  else
    Result := 'normal';
end;

function PWebTplModeOf(const S: RawUtf8; out Mode: TPWebTplMode): Boolean;
begin
  Mode := ptmNormal;
  Result := True;
  if S = 'normal' then
    exit;
  if S = 'executable' then
  begin
    Mode := ptmExecutable;
    exit;
  end;
  Result := False;
end;

function IntStr(Value: Int64): RawUtf8;
begin
  Result := RawUtf8(IntToStr(Value));
end;

function Pick(Cond: Boolean; const IfTrue, IfFalse: RawUtf8): RawUtf8;
begin
  if Cond then
    Result := IfTrue
  else
    Result := IfFalse;
end;

function PWebTplSha256Hex(const Data: RawByteString): RawUtf8;
begin
  Result := LowerCaseU(Sha256(Data));
end;

function PWebTplSha256HexValid(const S: RawUtf8): Boolean;
var
  i: PtrInt;
begin
  Result := False;
  if Length(S) <> 64 then
    exit;
  for i := 1 to 64 do
    if not (((S[i] >= '0') and (S[i] <= '9')) or
            ((S[i] >= 'a') and (S[i] <= 'f'))) then
      exit;
  Result := True;
end;

function PWebTplIdValid(const Id: RawUtf8): Boolean;
var
  i, len: PtrInt;
  prevDash: Boolean;
begin
  Result := False;
  len := Length(Id);
  if (len = 0) or
     (len > PWEB_TPL_ID_MAX_BYTES) then
    exit;
  if not ((Id[1] >= 'a') and (Id[1] <= 'z')) then
    exit;
  prevDash := False;
  for i := 2 to len do
    case Id[i] of
      'a'..'z', '0'..'9':
        prevDash := False;
      '-':
        begin
          if prevDash then
            exit; // no '--'
          prevDash := True;
        end;
    else
      exit;
    end;
  Result := not prevDash; // and no trailing '-'
end;

function PWebTplLayoutValid(const S: RawUtf8): Boolean;
var
  i: PtrInt;
begin
  Result := False;
  if (S = '') or
     (Length(S) > 32) then
    exit;
  for i := 1 to Length(S) do
    if not (((S[i] >= 'a') and (S[i] <= 'z')) or
            ((S[i] >= '0') and (S[i] <= '9'))) then
      exit;
  Result := True;
end;

{ The placeholder form, recognised in a PATH: a doubled opening brace, a
  NAME of upper-case ASCII letters and underscores, then a doubled closing
  brace. It is deliberately the ONLY shape this layer knows, and it knows
  nothing else about substitution - the token allowlist and the expansion
  itself belong to pweb.cli.scaffold. }
function StripPlaceholders(const Path: RawUtf8; out Clean: RawUtf8): Boolean;
var
  i, len, n: PtrInt;
  inTok: Boolean;
begin
  Clean := '';
  len := Length(Path);
  i := 1;
  inTok := False;
  n := 0;
  while i <= len do
  begin
    if (not inTok) and
       (i < len) and
       (Path[i] = '{') and
       (Path[i + 1] = '{') then
    begin
      inTok := True;
      Inc(i, 2);
      n := 0;
      continue;
    end;
    if inTok then
    begin
      if (i < len) and
         (Path[i] = '}') and
         (Path[i + 1] = '}') then
      begin
        if n = 0 then
          exit(False); // '{{}}' is not a token
        inTok := False;
        // a token stands for at least one character; substituting a single
        // ordinary letter lets the SHAPE of the surrounding path still be
        // checked here, while the VALUE is checked where it is known
        Clean := Clean + 'x';
        Inc(i, 2);
        continue;
      end;
      if not (((Path[i] >= 'A') and (Path[i] <= 'Z')) or
              (Path[i] = '_')) then
        exit(False);
      Inc(n);
      Inc(i);
      continue;
    end;
    if (Path[i] = '{') or
       (Path[i] = '}') then
      exit(False); // a lone brace is never a legal path character here
    Clean := Clean + Path[i];
    Inc(i);
  end;
  Result := not inTok; // an unterminated '{{' is a refusal
end;

function PWebTplPathValid(const Path: RawUtf8;
  Placeholders: Boolean): Boolean;
var
  probe, seg: RawUtf8;
  i, start, len: PtrInt;
begin
  Result := False;
  if (Path = '') or
     (Length(Path) > PWEB_TPL_PATH_MAX_BYTES) then
    exit;
  if Placeholders then
  begin
    if not StripPlaceholders(Path, probe) then
      exit;
  end
  else
  begin
    for i := 1 to Length(Path) do
      if (Path[i] = '{') or
         (Path[i] = '}') then
        exit; // a SOURCE path never carries a placeholder
    probe := Path;
  end;
  // the shared, ratified answer to "is this a canonical logical path".
  // Re-deciding any of it here would be a second answer to a settled
  // question, and the two would drift
  if not PWebAssetPathValid(probe) then
    exit;
  // this layer's own tighter segment bound, on top of it
  len := Length(probe);
  start := 1;
  for i := 1 to len + 1 do
    if (i > len) or
       (probe[i] = '/') then
    begin
      seg := Copy(probe, start, i - start);
      if Length(seg) > PWEB_TPL_SEGMENT_MAX_BYTES then
        exit;
      start := i + 1;
    end;
  Result := True;
end;

function PWebTplSegmentCount(const Path: RawUtf8): Integer;
var
  i: PtrInt;
begin
  Result := 1;
  for i := 1 to Length(Path) do
    if Path[i] = '/' then
      Inc(Result);
end;

{ ---------------- the secret / host-path classifiers --------------------- }

function AsciiLowerStr(const S: RawUtf8): RawUtf8;
var
  i: PtrInt;
begin
  // SetLength on Result gives a fresh buffer, so the source string is
  // never mutated in place through a shared reference
  SetLength(Result, Length(S));
  for i := 1 to Length(S) do
    if (S[i] >= 'A') and
       (S[i] <= 'Z') then
      Result[i] := AnsiChar(Ord(S[i]) + 32)
    else
      Result[i] := S[i];
end;

function ExtensionOf(const Name: RawUtf8): RawUtf8;
var
  i: PtrInt;
begin
  Result := '';
  for i := Length(Name) downto 1 do
    if Name[i] = '.' then
      exit(Copy(Name, i + 1, MaxInt));
end;

function StartsWith(const S, Prefix: RawUtf8): Boolean;
begin
  Result := (Length(S) >= Length(Prefix)) and
    (CompareStr(Copy(S, 1, Length(Prefix)), Prefix) = 0);
end;

function PWebTplSecretOutput(const Path: RawUtf8): Boolean;
var
  lower, seg, ext: RawUtf8;
  i, start, len: PtrInt;
begin
  Result := True;
  lower := AsciiLowerStr(Path);
  len := Length(lower);
  start := 1;
  for i := 1 to len + 1 do
    if (i > len) or
       (lower[i] = '/') then
    begin
      seg := Copy(lower, start, i - start);
      start := i + 1;
      if seg = '' then
        continue;
      // a dot-file is decided by an ALLOWLIST. A deny-list here would have
      // to anticipate every dotted credential convention that exists, and
      // the ones that matter are exactly the ones nobody listed
      if seg[1] = '.' then
      begin
        if (seg <> '.gitignore') and
           (seg <> '.gitattributes') and
           (seg <> '.editorconfig') then
          exit;
        continue;
      end;
      // trees and names a generated project must never carry as SOURCE
      if (seg = 'node_modules') or
         (seg = '__pycache__') or
         (seg = 'secrets') or
         (seg = 'credentials') or
         (seg = 'secrets.json') or
         (seg = 'credentials.json') or
         (seg = 'plugins.zip') or
         (seg = 'app.pwb') or
         (seg = 'thumbs.db') then
        exit;
      if StartsWith(seg, 'id_rsa') or
         StartsWith(seg, 'id_dsa') or
         StartsWith(seg, 'id_ecdsa') or
         StartsWith(seg, 'id_ed25519') then
        exit;
      // extensions: credentials, keys, databases, build outputs and native
      // binaries. A generated project ships SOURCE
      ext := ExtensionOf(seg);
      case ext of
        'pem', 'key', 'p12', 'pfx', 'jks', 'keystore', 'der', 'crt', 'cer',
        'db', 'sqlite', 'sqlite3', 'pwb', 'zip',
        'o', 'ppu', 'obj', 'a', 'lib', 'exe', 'dll', 'so', 'dylib',
        'compiled', 'bak':
          exit;
      end;
    end;
  Result := False;
end;

function ContainsAsciiFold(const Data: RawByteString;
  const Needle: RawUtf8): Boolean;
var
  i, j, dlen, nlen: PtrInt;
  c: AnsiChar;
  ok: Boolean;
begin
  Result := False;
  dlen := Length(Data);
  nlen := Length(Needle);
  if (nlen = 0) or
     (dlen < nlen) then
    exit;
  for i := 1 to dlen - nlen + 1 do
  begin
    ok := True;
    for j := 1 to nlen do
    begin
      c := Data[i + j - 1];
      if (c >= 'A') and
         (c <= 'Z') then
        c := AnsiChar(Ord(c) + 32);
      if c <> Needle[j] then
      begin
        ok := False;
        break;
      end;
    end;
    if ok then
      exit(True);
  end;
end;

function IsAsciiLetter(C: AnsiChar): Boolean; inline;
begin
  Result := ((C >= 'A') and (C <= 'Z')) or
            ((C >= 'a') and (C <= 'z'));
end;

function PWebTplHasHostPath(const Data: RawByteString): Boolean;
var
  i, len: PtrInt;
begin
  Result := True;
  len := Length(Data);
  // a Windows drive-letter path. The preceding byte must NOT be a letter,
  // a digit or a dot, or every 'https://' in every template README would
  // read as a drive called 's'
  for i := 1 to len - 2 do
    if IsAsciiLetter(Data[i]) and
       (Data[i + 1] = ':') and
       ((Data[i + 2] = '\') or (Data[i + 2] = '/')) then
      if (i = 1) or
         not (IsAsciiLetter(Data[i - 1]) or
              ((Data[i - 1] >= '0') and (Data[i - 1] <= '9')) or
              (Data[i - 1] = '.')) then
        exit;
  // the POSIX home and system trees, a UNC/long-path prefix, and the two
  // environment spellings of a home directory
  if ContainsAsciiFold(Data, '/users/') or
     ContainsAsciiFold(Data, '/home/') or
     ContainsAsciiFold(Data, '\users\') or
     ContainsAsciiFold(Data, '%userprofile%') or
     ContainsAsciiFold(Data, '$home') or
     ContainsAsciiFold(Data, '\\?\') or
     ContainsAsciiFold(Data, '/private/var/folders/') then
    exit;
  Result := False;
end;

function PWebTplTextValid(const Data: RawByteString;
  out Code: TPWebTplCode): Boolean;
var
  i: PtrInt;
begin
  Result := False;
  Code := ptcEntryEncoding;
  if Data = '' then
  begin
    Code := ptcEntryLineEnding; // a text template with no final newline
    exit;
  end;
  for i := 1 to Length(Data) do
    if Data[i] = #0 then
      exit; // an embedded NUL is never text
  // no BOM: it is invisible, it changes the bytes, and half the tools that
  // read a generated file would carry it into the next artifact
  if (Length(Data) >= 3) and
     (Data[1] = #$EF) and
     (Data[2] = #$BB) and
     (Data[3] = #$BF) then
    exit;
  // strict shortest-form UTF-8 - the same validator the descriptor reader,
  // the asset paths and the plugin manifests all use
  if not PWebStrictUtf8(RawUtf8(Data)) then
    exit;
  Code := ptcEntryLineEnding;
  for i := 1 to Length(Data) do
    if Data[i] = #13 then
      exit; // ONE line-ending policy: LF. A CR is a refusal, never a fixup
  if Data[Length(Data)] <> #10 then
    exit;
  if (Length(Data) >= 2) and
     (Data[Length(Data) - 1] = #10) then
    exit; // EXACTLY one terminating newline, so the rule is a rule
  Code := ptcNone;
  Result := True;
end;

{ ---------------- canonical projections ---------------------------------- }

function PWebTplInventoryText(const Inv: TPWebTplInventory): RawUtf8;
var
  i: PtrInt;
begin
  Result := '';
  for i := 0 to High(Inv) do
    Result := Result + Inv[i].Name + ' ' + IntStr(Inv[i].Bytes) + ' ' +
      Inv[i].Sha256 + #10;
end;

function PWebTplInventoryDigest(const Inv: TPWebTplInventory): RawUtf8;
begin
  Result := PWebTplSha256Hex(PWebTplInventoryText(Inv));
end;

function PWebTplRegistryText(const Reg: TPWebTemplateRegistry): RawUtf8;
var
  i: PtrInt;
begin
  Result := 'schema ' + IntStr(Reg.Schema) + #10 +
    'pack ' + Reg.PackFile + ' ' + IntStr(Reg.PackBytes) + ' ' +
      Reg.PackSha256 + #10 +
    'inventory ' + Reg.InventoryDigest + #10;
  for i := 0 to High(Reg.Templates) do
    Result := Result + 'template ' + Reg.Templates[i].Id + ' ' +
      Pick(Reg.Templates[i].IsPublic, 'public', 'private') + ' ' +
      Reg.Templates[i].Ui + ' ' + Reg.Templates[i].NativeDir + ' ' +
      Reg.Templates[i].NativeExt + ' ' + Reg.Templates[i].FrontendRoot +
      ' ' + Reg.Templates[i].OutputDir + ' ' +
      IntStr(Reg.Templates[i].FirstFile) + ' ' +
      IntStr(Reg.Templates[i].FileCount) + #10;
  for i := 0 to High(Reg.Files) do
    Result := Result + 'file ' + Reg.Files[i].Archive + ' ' +
      Reg.Files[i].OutPath + ' ' +
      PWebTplContentText(Reg.Files[i].Content) + ' ' +
      PWebTplModeText(Reg.Files[i].Mode) + ' ' +
      IntStr(Reg.Files[i].Bytes) + ' ' + Reg.Files[i].Sha256 + #10;
end;

function PWebTplRegistryDigest(const Reg: TPWebTemplateRegistry): RawUtf8;
begin
  Result := PWebTplSha256Hex(PWebTplRegistryText(Reg));
end;

{ ---------------- the trusted build-time list ---------------------------- }

type
  TListLine = record
    Key: RawUtf8;
    Value: RawUtf8;
    Number: Integer;
  end;
  TListLines = array of TListLine;

function ScanLines(const Bytes: RawByteString; out Lines: TListLines;
  out Code: TPWebTplCode; out Detail: RawUtf8): Boolean;
var
  i, start, len, n, eq, j: PtrInt;
  raw, key, value: RawUtf8;
  lineNo: Integer;
begin
  Lines := nil;
  Detail := '';
  Code := ptcNone;
  Result := False;
  len := Length(Bytes);
  if len > PWEB_TPL_LIST_MAX_BYTES then
  begin
    Code := ptcListTooLarge;
    exit;
  end;
  // ASCII only, and no control byte but LF. A build-time list that can
  // carry an escape, a CR or a non-ASCII homoglyph is a list whose review
  // does not mean what the reviewer thinks it means
  for i := 1 to len do
    if (Bytes[i] <> #10) and
       ((Bytes[i] < ' ') or (Bytes[i] > #126)) then
    begin
      Code := ptcListEncoding;
      Detail := 'byte ' + IntStr(i);
      exit;
    end;
  n := 0;
  lineNo := 0;
  start := 1;
  for i := 1 to len + 1 do
    if (i > len) or
       (Bytes[i] = #10) then
    begin
      Inc(lineNo);
      raw := Copy(RawUtf8(Bytes), start, i - start);
      start := i + 1;
      // a trailing space would make two visually identical lines differ
      if (raw <> '') and
         (raw[Length(raw)] = ' ') then
      begin
        Code := ptcListSyntax;
        Detail := 'trailing space on line ' + IntStr(lineNo);
        exit;
      end;
      j := 1;
      while (j <= Length(raw)) and
            (raw[j] = ' ') do
        Inc(j);
      raw := Copy(raw, j, MaxInt);
      if (raw = '') or
         (raw[1] = '#') then
        continue;
      eq := Pos(RawUtf8(' = '), raw);
      if eq = 0 then
      begin
        Code := ptcListSyntax;
        Detail := 'line ' + IntStr(lineNo) + ' is not `key = value`';
        exit;
      end;
      key := Copy(raw, 1, eq - 1);
      value := Copy(raw, eq + 3, MaxInt);
      if (key = '') or
         (value = '') or
         (Pos(RawUtf8(' '), key) > 0) or
         (Pos(RawUtf8(' '), value) > 0) then
      begin
        Code := ptcListSyntax;
        Detail := 'line ' + IntStr(lineNo) + ' has an empty or spaced field';
        exit;
      end;
      SetLength(Lines, n + 1);
      Lines[n].Key := key;
      Lines[n].Value := value;
      Lines[n].Number := lineNo;
      Inc(n);
    end;
  Result := True;
end;

function PWebTplParseList(const Bytes: RawByteString;
  out Templates: TPWebTrustedTemplates; out Files: TPWebTrustedFiles;
  out Code: TPWebTplCode; out Detail: RawUtf8): Boolean;
var
  lines: TListLines;
  i, j, t, f: PtrInt;
  seenSchema, inTemplate, inFile, complete: Boolean;
  seen: TRawUtf8DynArray;
  sn: PtrInt;

  function Mark(const Key: RawUtf8): Boolean;
  var
    k: PtrInt;
  begin
    for k := 0 to sn - 1 do
      if seen[k] = Key then
        exit(False);
    SetLength(seen, sn + 1);
    seen[sn] := Key;
    Inc(sn);
    Result := True;
  end;

begin
  Templates := nil;
  Files := nil;
  Detail := '';
  Code := ptcNone;
  Result := False;
  if not ScanLines(Bytes, lines, Code, Detail) then
    exit;
  seenSchema := False;
  inTemplate := False;
  inFile := False;
  t := -1;
  f := -1;
  seen := nil;
  sn := 0;
  for i := 0 to High(lines) do
  begin
    if lines[i].Key = 'schema' then
    begin
      if seenSchema or inTemplate then
      begin
        Code := ptcListSyntax;
        Detail := 'schema must appear exactly once, first';
        exit;
      end;
      if lines[i].Value <> IntStr(PWEB_TPL_SCHEMA) then
      begin
        Code := ptcListSchema;
        Detail := lines[i].Value;
        exit;
      end;
      seenSchema := True;
      continue;
    end;
    if not seenSchema then
    begin
      Code := ptcListSchema;
      Detail := 'the list does not open with a schema line';
      exit;
    end;
    if lines[i].Key = 'template' then
    begin
      if inTemplate then
      begin
        complete := (Templates[t].Ui <> '') and
          (Templates[t].NativeDir <> '') and (Templates[t].NativeExt <> '') and
          (Templates[t].FrontendRoot <> '') and (Templates[t].OutputDir <> '');
        if not complete then
        begin
          Code := ptcListMissingField;
          Detail := 'template ' + Templates[t].Id;
          exit;
        end;
      end;
      if not PWebTplIdValid(lines[i].Value) then
      begin
        Code := ptcListTemplateId;
        Detail := lines[i].Value;
        exit;
      end;
      for j := 0 to High(Templates) do
        if Templates[j].Id = lines[i].Value then
        begin
          Code := ptcListDuplicate;
          Detail := 'template ' + lines[i].Value;
          exit;
        end;
      t := Length(Templates);
      if t >= PWEB_TPL_MAX_TEMPLATES then
      begin
        Code := ptcListCount;
        Detail := 'templates';
        exit;
      end;
      SetLength(Templates, t + 1);
      Templates[t] := Default(TPWebTrustedTemplate);
      Templates[t].Id := lines[i].Value;
      inTemplate := True;
      inFile := False;
      seen := nil;
      sn := 0;
      continue;
    end;
    if not inTemplate then
    begin
      Code := ptcListSyntax;
      Detail := 'line ' + IntStr(lines[i].Number) + ' precedes any template';
      exit;
    end;
    if lines[i].Key = 'file' then
    begin
      complete := (Templates[t].Ui <> '') and
        (Templates[t].NativeDir <> '') and (Templates[t].NativeExt <> '') and
        (Templates[t].FrontendRoot <> '') and (Templates[t].OutputDir <> '');
      if not complete then
      begin
        Code := ptcListMissingField;
        Detail := 'template ' + Templates[t].Id;
        exit;
      end;
      if not PWebTplPathValid(lines[i].Value, {Placeholders=}False) then
      begin
        Code := ptcListSource;
        Detail := lines[i].Value;
        exit;
      end;
      for j := 0 to High(Files) do
        if (Files[j].Template = Templates[t].Id) and
           (Files[j].Source = lines[i].Value) then
        begin
          Code := ptcListDuplicate;
          Detail := 'source ' + lines[i].Value;
          exit;
        end;
      f := Length(Files);
      if f >= PWEB_TPL_MAX_ENTRIES then
      begin
        Code := ptcListCount;
        Detail := 'files';
        exit;
      end;
      SetLength(Files, f + 1);
      Files[f] := Default(TPWebTrustedFile);
      Files[f].Template := Templates[t].Id;
      Files[f].Source := lines[i].Value;
      inFile := True;
      seen := nil;
      sn := 0;
      continue;
    end;
    if not Mark(lines[i].Key) then
    begin
      Code := ptcListDuplicateKey;
      Detail := lines[i].Key + ' on line ' + IntStr(lines[i].Number);
      exit;
    end;
    if inFile then
    begin
      if lines[i].Key = 'out' then
      begin
        if not PWebTplPathValid(lines[i].Value, {Placeholders=}True) then
        begin
          Code := ptcListOutput;
          Detail := lines[i].Value;
          exit;
        end;
        Files[f].OutPath := lines[i].Value;
      end
      else if lines[i].Key = 'content' then
      begin
        if not PWebTplContentOf(lines[i].Value, Files[f].Content) then
        begin
          Code := ptcListContent;
          Detail := lines[i].Value;
          exit;
        end;
        Files[f].HasContent := True;
      end
      else if lines[i].Key = 'mode' then
      begin
        if not PWebTplModeOf(lines[i].Value, Files[f].Mode) then
        begin
          Code := ptcListMode;
          Detail := lines[i].Value;
          exit;
        end;
        Files[f].HasMode := True;
      end
      else
      begin
        Code := ptcListUnknownField;
        Detail := lines[i].Key;
        exit;
      end;
      continue;
    end;
    if lines[i].Key = 'visibility' then
    begin
      if lines[i].Value = 'public' then
        Templates[t].IsPublic := True
      else if lines[i].Value <> 'private' then
      begin
        Code := ptcListVisibility;
        Detail := lines[i].Value;
        exit;
      end;
    end
    else if lines[i].Key = 'ui' then
    begin
      // exactly the schema-1 vocabulary: a template cannot invent a third
      if (lines[i].Value <> 'react') and
         (lines[i].Value <> 'pas2js') then
      begin
        Code := ptcListUi;
        Detail := lines[i].Value;
        exit;
      end;
      Templates[t].Ui := lines[i].Value;
    end
    else if (lines[i].Key = 'native-dir') or
            (lines[i].Key = 'native-ext') or
            (lines[i].Key = 'frontend-root') or
            (lines[i].Key = 'output-dir') then
    begin
      if not PWebTplLayoutValid(lines[i].Value) then
      begin
        Code := ptcListLayout;
        Detail := lines[i].Key + ' = ' + lines[i].Value;
        exit;
      end;
      if lines[i].Key = 'native-dir' then
        Templates[t].NativeDir := lines[i].Value
      else if lines[i].Key = 'native-ext' then
        Templates[t].NativeExt := lines[i].Value
      else if lines[i].Key = 'frontend-root' then
        Templates[t].FrontendRoot := lines[i].Value
      else
        Templates[t].OutputDir := lines[i].Value;
    end
    else
    begin
      Code := ptcListUnknownField;
      Detail := lines[i].Key;
      exit;
    end;
  end;
  if not seenSchema then
  begin
    Code := ptcListSchema;
    exit;
  end;
  if (not inTemplate) or
     (Length(Templates) = 0) or
     (Length(Files) = 0) then
  begin
    Code := ptcListEmpty;
    exit;
  end;
  complete := (Templates[t].Ui <> '') and
    (Templates[t].NativeDir <> '') and (Templates[t].NativeExt <> '') and
    (Templates[t].FrontendRoot <> '') and (Templates[t].OutputDir <> '');
  if not complete then
  begin
    Code := ptcListMissingField;
    Detail := 'template ' + Templates[t].Id;
    exit;
  end;
  // EVERY file row must have been described completely. An omitted content
  // or mode would otherwise take a silent default, which is the exact
  // inference this list exists to replace
  for i := 0 to High(Files) do
  begin
    if Files[i].OutPath = '' then
    begin
      Code := ptcListMissingField;
      Detail := 'out for ' + Files[i].Template + '/' + Files[i].Source;
      exit;
    end;
    if not Files[i].HasContent then
    begin
      Code := ptcListMissingField;
      Detail := 'content for ' + Files[i].Template + '/' + Files[i].Source;
      exit;
    end;
    if not Files[i].HasMode then
    begin
      Code := ptcListMissingField;
      Detail := 'mode for ' + Files[i].Template + '/' + Files[i].Source;
      exit;
    end;
  end;
  // and no two files of one template may render to the same literal output
  for i := 0 to High(Files) do
    for j := i + 1 to High(Files) do
      if (Files[i].Template = Files[j].Template) and
         (Files[i].OutPath = Files[j].OutPath) then
      begin
        Code := ptcListDuplicate;
        Detail := 'output ' + Files[i].OutPath;
        exit;
      end;
  Code := ptcNone;
  Result := True;
end;

{ ---------------- the deterministic pack writer -------------------------- }

function SortEntries(var Entries: TPWebTplEntries): Boolean;
var
  i, j: PtrInt;
  tmp: TPWebTplEntry;
begin
  // an insertion sort over the canonical names. Small n, and being obvious
  // matters more here than being fast: this order IS the archive
  for i := 1 to High(Entries) do
  begin
    tmp := Entries[i];
    j := i - 1;
    while (j >= 0) and
          (CompareStr(Entries[j].Name, tmp.Name) > 0) do
    begin
      Entries[j + 1] := Entries[j];
      Dec(j);
    end;
    Entries[j + 1] := tmp;
  end;
  Result := True;
  for i := 1 to High(Entries) do
    if Entries[i].Name = Entries[i - 1].Name then
      exit(False);
end;

function UnderAnyRoot(const Name: RawUtf8;
  const Roots: TRawUtf8DynArray): Boolean;
var
  i: PtrInt;
begin
  Result := True;
  for i := 0 to High(Roots) do
    if (Length(Name) > Length(Roots[i])) and
       StartsWith(Name, Roots[i]) then
      exit;
  Result := False;
end;

function PWebTplWritePack(const OutFile: RawUtf8;
  const Entries: TPWebTplEntries; const Roots: TRawUtf8DynArray;
  out Inv: TPWebTplInventory; out PackSha256: RawUtf8; out PackBytes: Int64;
  out Code: TPWebTplCode; out Detail: RawUtf8): Boolean;
var
  sorted: TPWebTplEntries;
  folded: TRawUtf8DynArray;
  i, j, n: PtrInt;
  tmp: RawUtf8;
  zw: TZipWrite;
  zr: TZipRead;
  obj: TZipAssetStore;
  store: IAssetStore;
  asset: TAssetResponse;
  raw: RawUtf8;
  data: RawByteString;
  total: Int64;
begin
  Inv := nil;
  PackSha256 := '';
  PackBytes := 0;
  Detail := '';
  Result := False;
  n := Length(Entries);
  if n = 0 then
  begin
    Code := ptcListEmpty;
    exit;
  end;
  if n > PWEB_TPL_MAX_ENTRIES then
  begin
    Code := ptcEntryCount;
    Detail := IntStr(n);
    exit;
  end;
  sorted := Copy(Entries, 0, n);
  if not SortEntries(sorted) then
  begin
    Code := ptcEntryDuplicate;
    exit;
  end;
  total := 0;
  for i := 0 to n - 1 do
  begin
    if not PWebTplPathValid(sorted[i].Name, {Placeholders=}False) then
    begin
      Code := ptcEntryName;
      Detail := sorted[i].Name;
      exit;
    end;
    if not UnderAnyRoot(sorted[i].Name, Roots) then
    begin
      Code := ptcEntryOutsideRoot;
      Detail := sorted[i].Name;
      exit;
    end;
    if Length(sorted[i].Content) > PWEB_TPL_FILE_MAX_BYTES then
    begin
      Code := ptcEntryTooLarge;
      Detail := sorted[i].Name;
      exit;
    end;
    Inc(total, Length(sorted[i].Content));
    // TZipWrite takes native TFileName entry names; require an exact byte
    // round-trip so the codepage hazard fails loudly HERE rather than
    // becoming a mangled name inside the archive
    if StringToUtf8(Utf8ToString(sorted[i].Name)) <> sorted[i].Name then
    begin
      Code := ptcEntryCodepage;
      Detail := sorted[i].Name;
      exit;
    end;
  end;
  if total > PWEB_TPL_PACK_MAX_BYTES then
  begin
    Code := ptcEntryTooLarge;
    Detail := 'pack total ' + IntStr(total);
    exit;
  end;
  // ratified CAP-6 D1: two names equal under the pinned mORMot Unicode 10.0
  // simple case fold are ambiguous and reject the build. The fold is a
  // collision VERDICT and never rewrites a name; the tables are compiled
  // in, so the verdict is identical on every machine
  SetLength(folded, n);
  for i := 0 to n - 1 do
    folded[i] := UpperCaseReference(sorted[i].Name);
  for i := 0 to n - 1 do
    for j := i + 1 to n - 1 do
      if folded[i] = folded[j] then
      begin
        Code := ptcEntryCollision;
        Detail := sorted[i].Name + ' vs ' + sorted[j].Name;
        exit;
      end;
  // a name that is also a directory prefix of another cannot exist in any
  // folder layout - ambiguous, rejected
  for i := 0 to n - 1 do
    for j := 0 to n - 1 do
      if (i <> j) and
         (Length(sorted[j].Name) > Length(sorted[i].Name) + 1) and
         StartsWith(sorted[j].Name, sorted[i].Name) and
         (sorted[j].Name[Length(sorted[i].Name) + 1] = '/') then
      begin
        Code := ptcEntryCollision;
        Detail := sorted[i].Name + ' vs ' + sorted[j].Name;
        exit;
      end;
  // ---- the write, into a temp sibling ----
  tmp := OutFile + '.tmp';
  Code := ptcArchiveWrite;
  try
    SysUtils.DeleteFile(Utf8ToString(tmp)); // stale temp of a killed run
    zw := TZipWrite.Create(Utf8ToString(tmp));
    try
      for i := 0 to n - 1 do
        // STORED, never deflated: see the unit header. No compressor is
        // reached, so nothing toolchain-specific can enter these bytes
        zw.AddStored(Utf8ToString(sorted[i].Name),
          pointer(sorted[i].Content), Length(sorted[i].Content),
          PWEB_BUNDLE_FIXED_FILE_AGE);
      if zw.NeedZip64 then
      begin
        Detail := 'zip64 would break the deterministic format';
        exit;
      end;
    finally
      zw.Free;
    end;
    // ---- self-validation 1: the raw archive record, field by field ----
    zr := TZipRead.Create(Utf8ToString(tmp));
    try
      if zr.Count <> n then
      begin
        Detail := 'entry count drifted';
        exit;
      end;
      for i := 0 to n - 1 do
      begin
        FastSetString(raw, zr.Entry[i].storedName,
          zr.Entry[i].dir^.fileInfo.nameLen);
        if raw <> sorted[i].Name then
        begin
          Detail := 'stored name drifted: ' + raw;
          exit;
        end;
        if zr.Entry[i].dir^.fileInfo.zzipMethod <> PWEB_TPL_ZIP_STORED then
        begin
          Detail := 'entry is not stored: ' + sorted[i].Name;
          exit;
        end;
        if zr.Entry[i].dir^.fileInfo.zlastMod <>
             PWEB_BUNDLE_FIXED_FILE_AGE then
        begin
          Detail := 'non-deterministic timestamp: ' + sorted[i].Name;
          exit;
        end;
        if zr.Entry[i].dir^.fileInfo.extraLen <> 0 then
        begin
          Detail := 'unexpected extra field: ' + sorted[i].Name;
          exit;
        end;
      end;
    finally
      zr.Free;
    end;
    // ---- self-validation 2: the PRODUCTION reader must accept it, and
    // every byte must serve back identically ----
    data := StringFromFile(Utf8ToString(tmp));
    if data = '' then
    begin
      Detail := 'the fresh pack read back empty';
      exit;
    end;
    obj := nil;
    try
      obj := TZipAssetStore.CreateFromBuffer(data);
    except
      on E: Exception do
      begin
        Detail := 'the production store refused the fresh pack';
        exit;
      end;
    end;
    store := obj; // from here the interface owns the instance
    SetLength(Inv, n);
    for i := 0 to n - 1 do
    begin
      if not store.TryRead(sorted[i].Name, asset) then
      begin
        Detail := 'entry unreadable: ' + sorted[i].Name;
        Inv := nil;
        exit;
      end;
      if asset.Content <> sorted[i].Content then
      begin
        Detail := 'content drifted: ' + sorted[i].Name;
        Inv := nil;
        exit;
      end;
      Inv[i].Name := sorted[i].Name;
      Inv[i].Bytes := Length(sorted[i].Content);
      Inv[i].Sha256 := PWebTplSha256Hex(sorted[i].Content);
    end;
    store := nil; // release the buffer before the replace
    PackSha256 := PWebTplSha256Hex(data);
    PackBytes := Length(data);
    if not PWebCliReplaceFile(tmp, OutFile) then
    begin
      Detail := 'the atomic replace failed';
      Inv := nil;
      PackSha256 := '';
      PackBytes := 0;
      exit;
    end;
  finally
    store := nil;
    SysUtils.DeleteFile(Utf8ToString(tmp));
  end;
  Code := ptcNone;
  Result := True;
end;

{ ---------------- registry assembly and validation ----------------------- }

function PWebTplRegistryFrom(const PackFile, PackSha256: RawUtf8;
  PackBytes: Int64; const InventoryDigest: RawUtf8;
  const Inv: array of TPWebTplInventoryEntry;
  const Files: array of TPWebTplFile;
  const Templates: array of TPWebTplTemplate): TPWebTemplateRegistry;
var
  i: PtrInt;
begin
  Result := Default(TPWebTemplateRegistry);
  Result.Schema := PWEB_TPL_SCHEMA;
  Result.PackFile := PackFile;
  Result.PackSha256 := PackSha256;
  Result.PackBytes := PackBytes;
  Result.InventoryDigest := InventoryDigest;
  SetLength(Result.Inventory, Length(Inv));
  for i := 0 to High(Inv) do
    Result.Inventory[i] := Inv[i];
  SetLength(Result.Files, Length(Files));
  for i := 0 to High(Files) do
    Result.Files[i] := Files[i];
  SetLength(Result.Templates, Length(Templates));
  for i := 0 to High(Templates) do
    Result.Templates[i] := Templates[i];
end;

function PWebTplValidateRegistry(const Reg: TPWebTemplateRegistry;
  out Code: TPWebTplCode; out Detail: RawUtf8): Boolean;
var
  i, j, t, k: PtrInt;
  root: RawUtf8;
  ok: Boolean;
  claims: Integer;
begin
  Detail := '';
  Code := ptcRegistry;
  Result := False;
  if Reg.Schema <> PWEB_TPL_SCHEMA then
  begin
    Detail := 'schema ' + IntStr(Reg.Schema);
    exit;
  end;
  if (Reg.PackFile = '') or
     (Pos(RawUtf8('/'), Reg.PackFile) > 0) or
     (Pos(RawUtf8('\'), Reg.PackFile) > 0) then
  begin
    Detail := 'pack file name';
    exit;
  end;
  if not PWebTplSha256HexValid(Reg.PackSha256) then
  begin
    Detail := 'pack digest shape';
    exit;
  end;
  if (Reg.PackBytes <= 0) or
     (Reg.PackBytes > PWEB_TPL_PACK_MAX_BYTES) then
  begin
    Detail := 'pack bytes ' + IntStr(Reg.PackBytes);
    exit;
  end;
  if not PWebTplSha256HexValid(Reg.InventoryDigest) then
  begin
    Detail := 'inventory digest shape';
    exit;
  end;
  if (Length(Reg.Inventory) = 0) or
     (Length(Reg.Inventory) > PWEB_TPL_MAX_ENTRIES) then
  begin
    Detail := 'inventory count';
    exit;
  end;
  if (Length(Reg.Templates) = 0) or
     (Length(Reg.Templates) > PWEB_TPL_MAX_TEMPLATES) then
  begin
    Detail := 'template count';
    exit;
  end;
  if Length(Reg.Files) <> Length(Reg.Inventory) then
  begin
    Detail := 'file rows and inventory rows disagree in number';
    exit;
  end;
  // the inventory is globally sorted bytewise, strictly, with no duplicate
  for i := 0 to High(Reg.Inventory) do
  begin
    if not PWebTplPathValid(Reg.Inventory[i].Name, False) then
    begin
      Detail := 'inventory name ' + Reg.Inventory[i].Name;
      exit;
    end;
    if not PWebTplSha256HexValid(Reg.Inventory[i].Sha256) then
    begin
      Detail := 'inventory digest for ' + Reg.Inventory[i].Name;
      exit;
    end;
    if (Reg.Inventory[i].Bytes < 0) or
       (Reg.Inventory[i].Bytes > PWEB_TPL_FILE_MAX_BYTES) then
    begin
      Detail := 'inventory size for ' + Reg.Inventory[i].Name;
      exit;
    end;
    if (i > 0) and
       (CompareStr(Reg.Inventory[i - 1].Name,
          Reg.Inventory[i].Name) >= 0) then
    begin
      Detail := 'inventory order at ' + Reg.Inventory[i].Name;
      exit;
    end;
  end;
  if PWebTplInventoryDigest(Reg.Inventory) <> Reg.InventoryDigest then
  begin
    Detail := 'the inventory digest does not describe the inventory';
    exit;
  end;
  // templates: sorted, unique, complete, and their slices coherent
  for t := 0 to High(Reg.Templates) do
  begin
    if not PWebTplIdValid(Reg.Templates[t].Id) then
    begin
      Detail := 'template id ' + Reg.Templates[t].Id;
      exit;
    end;
    if (t > 0) and
       (CompareStr(Reg.Templates[t - 1].Id, Reg.Templates[t].Id) >= 0) then
    begin
      Detail := 'template order at ' + Reg.Templates[t].Id;
      exit;
    end;
    if (Reg.Templates[t].Ui <> 'react') and
       (Reg.Templates[t].Ui <> 'pas2js') then
    begin
      Detail := 'template ui ' + Reg.Templates[t].Ui;
      exit;
    end;
    if not (PWebTplLayoutValid(Reg.Templates[t].NativeDir) and
            PWebTplLayoutValid(Reg.Templates[t].NativeExt) and
            PWebTplLayoutValid(Reg.Templates[t].FrontendRoot) and
            PWebTplLayoutValid(Reg.Templates[t].OutputDir)) then
    begin
      Detail := 'template layout for ' + Reg.Templates[t].Id;
      exit;
    end;
    if (Reg.Templates[t].FileCount <= 0) or
       (Reg.Templates[t].FileCount > PWEB_TPL_MAX_OUTPUT_FILES) or
       (Reg.Templates[t].FirstFile < 0) or
       (Reg.Templates[t].FirstFile + Reg.Templates[t].FileCount >
          Length(Reg.Files)) then
    begin
      Detail := 'template slice for ' + Reg.Templates[t].Id;
      exit;
    end;
    if t = 0 then
    begin
      if Reg.Templates[t].FirstFile <> 0 then
      begin
        Detail := 'the first template slice does not start at 0';
        exit;
      end;
    end
    else if Reg.Templates[t].FirstFile <> Reg.Templates[t - 1].FirstFile +
              Reg.Templates[t - 1].FileCount then
    begin
      Detail := 'template slices are not contiguous at ' +
        Reg.Templates[t].Id;
      exit;
    end;
    if (t = High(Reg.Templates)) and
       (Reg.Templates[t].FirstFile + Reg.Templates[t].FileCount <>
          Length(Reg.Files)) then
    begin
      Detail := 'the template slices do not cover every file row';
      exit;
    end;
    root := Reg.Templates[t].Id + '/';
    for i := Reg.Templates[t].FirstFile to
             Reg.Templates[t].FirstFile + Reg.Templates[t].FileCount - 1 do
    begin
      if not PWebTplPathValid(Reg.Files[i].Archive, False) then
      begin
        Detail := 'file archive name ' + Reg.Files[i].Archive;
        exit;
      end;
      // membership of its OWN template's root: a file row can never point
      // at another template's bytes
      if (Length(Reg.Files[i].Archive) <= Length(root)) or
         not StartsWith(Reg.Files[i].Archive, root) then
      begin
        Detail := Reg.Files[i].Archive + ' is not under ' + root;
        exit;
      end;
      if not PWebTplPathValid(Reg.Files[i].OutPath, True) then
      begin
        Detail := 'file output ' + Reg.Files[i].OutPath;
        exit;
      end;
      if PWebTplSecretOutput(Reg.Files[i].OutPath) then
      begin
        Code := ptcEntrySecret;
        Detail := Reg.Files[i].OutPath;
        exit;
      end;
      if not PWebTplSha256HexValid(Reg.Files[i].Sha256) then
      begin
        Detail := 'file digest for ' + Reg.Files[i].Archive;
        exit;
      end;
      if (i > Reg.Templates[t].FirstFile) and
         (CompareStr(Reg.Files[i - 1].Archive,
            Reg.Files[i].Archive) >= 0) then
      begin
        Detail := 'file order at ' + Reg.Files[i].Archive;
        exit;
      end;
      for j := Reg.Templates[t].FirstFile to i - 1 do
        if Reg.Files[j].OutPath = Reg.Files[i].OutPath then
        begin
          Detail := 'duplicate output ' + Reg.Files[i].OutPath;
          exit;
        end;
      // and the row must describe an inventory entry EXACTLY
      ok := False;
      for j := 0 to High(Reg.Inventory) do
        if Reg.Inventory[j].Name = Reg.Files[i].Archive then
        begin
          ok := (Reg.Inventory[j].Bytes = Reg.Files[i].Bytes) and
            (Reg.Inventory[j].Sha256 = Reg.Files[i].Sha256);
          break;
        end;
      if not ok then
      begin
        Detail := 'file row disagrees with the inventory: ' +
          Reg.Files[i].Archive;
        exit;
      end;
    end;
  end;
  // and every inventory entry must be claimed by exactly one file row
  for i := 0 to High(Reg.Inventory) do
  begin
    claims := 0;
    for k := 0 to High(Reg.Files) do
      if Reg.Files[k].Archive = Reg.Inventory[i].Name then
        Inc(claims);
    if claims <> 1 then
    begin
      Detail := IntStr(claims) + ' file rows claim ' + Reg.Inventory[i].Name;
      exit;
    end;
  end;
  Code := ptcNone;
  Result := True;
end;

{ ---------------- the generated native registry emitter ------------------ }

function EmittableAscii(const S: RawUtf8): Boolean;
var
  i: PtrInt;
begin
  // printable ASCII, no quote and no backslash. An emitted string can then
  // never terminate its own literal, continue a line, or become a
  // directive. A violation is a REFUSAL, never an escape - escaping is how
  // a generator becomes the place where arbitrary text turns into code
  Result := False;
  if (S = '') or
     (Length(S) > 512) then
    exit;
  for i := 1 to Length(S) do
    if (S[i] < ' ') or
       (S[i] > #126) or
       (S[i] = '''') or
       (S[i] = '\') then
      exit;
  Result := True;
end;

function PWebTplEmitRegistry(const Reg: TPWebTemplateRegistry;
  const ToolId: RawUtf8; out Text: RawUtf8;
  out Code: TPWebTplCode; out Detail: RawUtf8): Boolean;
var
  i: PtrInt;
  s: RawUtf8;

  function Q(const V: RawUtf8): RawUtf8;
  begin
    if not EmittableAscii(V) then
      raise EPWebTemplate.Create('value is not safely emittable as Pascal');
    Result := '''' + V + '''';
  end;

begin
  Text := '';
  Detail := '';
  Result := False;
  // NEVER emit a registry that would not survive its own gate
  if not PWebTplValidateRegistry(Reg, Code, Detail) then
    exit;
  Code := ptcRegistryEmit;
  if not EmittableAscii(ToolId) then
  begin
    Detail := 'tool id';
    exit;
  end;
  try
    s := '{ GENERATED - DO NOT EDIT.' + #10 +
      '  CAP-10B0 trusted template registry, produced by ' + ToolId + '.' +
      #10 + #10 +
      '  This include is the TRUST ANCHOR for the template pack: every' + #10 +
      '  name, output path, content kind, file mode, byte length and' + #10 +
      '  digest below is a compiled constant, so the archive it describes' +
      #10 +
      '  carries bytes and is believed about nothing else.' + #10 + #10 +
      '  It carries no absolute path, no timestamp and no host name, so' + #10 +
      '  regenerating it from the same trusted source is byte-identical.' +
      #10 +
      '  WRITEABLECONST is OFF around the whole block: these are read-only' +
      #10 +
      '  storage and nothing at runtime may assign to them. }' + #10 + #10 +
      '{$PUSH}' + #10 +
      '{$WRITEABLECONST OFF}' + #10 +
      'const' + #10 +
      '  PWEB_TPL_GEN_SCHEMA = ' + IntStr(Reg.Schema) + ';' + #10 +
      '  PWEB_TPL_GEN_PACK_FILE = ' + Q(Reg.PackFile) + ';' + #10 +
      '  PWEB_TPL_GEN_PACK_SHA256 = ' + Q(Reg.PackSha256) + ';' + #10 +
      '  PWEB_TPL_GEN_PACK_BYTES = Int64(' + IntStr(Reg.PackBytes) + ');' +
      #10 +
      '  PWEB_TPL_GEN_INVENTORY_DIGEST = ' + Q(Reg.InventoryDigest) + ';' +
      #10 + #10 +
      '  PWEB_TPL_GEN_INVENTORY: array[0 .. ' +
        IntStr(High(Reg.Inventory)) + '] of TPWebTplInventoryEntry = (' + #10;
    for i := 0 to High(Reg.Inventory) do
    begin
      s := s + '    (Name: ' + Q(Reg.Inventory[i].Name) +
        '; Bytes: ' + IntStr(Reg.Inventory[i].Bytes) +
        '; Sha256: ' + Q(Reg.Inventory[i].Sha256) + ')';
      if i < High(Reg.Inventory) then
        s := s + ',';
      s := s + #10;
    end;
    s := s + '  );' + #10 + #10 +
      '  PWEB_TPL_GEN_FILES: array[0 .. ' + IntStr(High(Reg.Files)) +
        '] of TPWebTplFile = (' + #10;
    for i := 0 to High(Reg.Files) do
    begin
      s := s + '    (Archive: ' + Q(Reg.Files[i].Archive) +
        '; OutPath: ' + Q(Reg.Files[i].OutPath) + ';' + #10 +
        '     Content: ' +
          Pick(Reg.Files[i].Content = ptkBinary, 'ptkBinary', 'ptkText') +
        '; Mode: ' +
          Pick(Reg.Files[i].Mode = ptmExecutable,
            'ptmExecutable', 'ptmNormal') +
        '; Bytes: ' + IntStr(Reg.Files[i].Bytes) +
        '; Sha256: ' + Q(Reg.Files[i].Sha256) + ')';
      if i < High(Reg.Files) then
        s := s + ',';
      s := s + #10;
    end;
    s := s + '  );' + #10 + #10 +
      '  PWEB_TPL_GEN_TEMPLATES: array[0 .. ' + IntStr(High(Reg.Templates)) +
        '] of TPWebTplTemplate = (' + #10;
    for i := 0 to High(Reg.Templates) do
    begin
      s := s + '    (Id: ' + Q(Reg.Templates[i].Id) +
        '; IsPublic: ' + Pick(Reg.Templates[i].IsPublic, 'True', 'False') +
        '; Ui: ' + Q(Reg.Templates[i].Ui) + ';' + #10 +
        '     NativeDir: ' + Q(Reg.Templates[i].NativeDir) +
        '; NativeExt: ' + Q(Reg.Templates[i].NativeExt) +
        '; FrontendRoot: ' + Q(Reg.Templates[i].FrontendRoot) + ';' + #10 +
        '     OutputDir: ' + Q(Reg.Templates[i].OutputDir) +
        '; FirstFile: ' + IntStr(Reg.Templates[i].FirstFile) +
        '; FileCount: ' + IntStr(Reg.Templates[i].FileCount) + ')';
      if i < High(Reg.Templates) then
        s := s + ',';
      s := s + #10;
    end;
    s := s + '  );' + #10 +
      '{$POP}' + #10;
  except
    on E: EPWebTemplate do
    begin
      Detail := RawUtf8(E.Message);
      exit;
    end;
  end;
  Text := s;
  Code := ptcNone;
  Result := True;
end;

{ ---------------- lookup and runtime verification ------------------------ }

function PWebTplFind(const Reg: TPWebTemplateRegistry; const Id: RawUtf8;
  RequirePublic: Boolean; out Index: Integer;
  out Code: TPWebTplCode): Boolean;
var
  i: PtrInt;
begin
  Index := -1;
  Code := ptcTemplateUnknown;
  Result := False;
  for i := 0 to High(Reg.Templates) do
    if Reg.Templates[i].Id = Id then
    begin
      if RequirePublic and
         not Reg.Templates[i].IsPublic then
      begin
        // a private template is refused with its OWN code: "there is no
        // such template" and "that one is not yours to ask for" are
        // different answers, and a public command must give the second
        Code := ptcTemplatePrivate;
        exit;
      end;
      Index := i;
      Code := ptcNone;
      exit(True);
    end;
end;

function PWebTplLoadPack(const PackPath: RawUtf8; out Data: RawByteString;
  out PackSha256: RawUtf8; out Code: TPWebTplCode): Boolean;
var
  tooBig: Boolean;
begin
  Data := '';
  PackSha256 := '';
  Result := False;
  if not PWebCliReadSmallFile(PackPath, PWEB_TPL_PACK_MAX_BYTES,
       Data, tooBig) then
  begin
    if tooBig then
      Code := ptcPackSize
    else
      Code := ptcArchiveInvalid;
    exit;
  end;
  if Data = '' then
  begin
    Code := ptcPackSize;
    exit;
  end;
  PackSha256 := PWebTplSha256Hex(Data);
  Code := ptcNone;
  Result := True;
end;

function PWebTplVerifyPack(const Reg: TPWebTemplateRegistry;
  const PackData: RawByteString; const PackSha256: RawUtf8;
  out Store: IAssetStore; out Code: TPWebTplCode;
  out Detail: RawUtf8): Boolean;
var
  obj: TZipAssetStore;
  probe: IAssetStore;
  asset: TAssetResponse;
  i: PtrInt;
begin
  Store := nil;
  Detail := '';
  Result := False;
  // 1. the registry must be self-consistent before it is trusted to judge
  //    anything at all
  if not PWebTplValidateRegistry(Reg, Code, Detail) then
    exit;
  // 2. exact length, then exact digest, both against the bytes the caller
  //    already read ONCE while hashing them. Nothing here re-reads a file,
  //    so there is no second set of bytes to disagree
  if Length(PackData) <> Reg.PackBytes then
  begin
    Code := ptcPackSize;
    Detail := IntStr(Length(PackData)) + ' vs ' + IntStr(Reg.PackBytes);
    exit;
  end;
  if (not PWebTplSha256HexValid(PackSha256)) or
     (PackSha256 <> Reg.PackSha256) then
  begin
    Code := ptcPackDigest;
    exit;
  end;
  // 3. the PRODUCTION store, over THOSE SAME BYTES
  obj := nil;
  try
    obj := TZipAssetStore.CreateFromBuffer(PackData);
  except
    on E: Exception do
    begin
      Code := ptcArchiveInvalid;
      Detail := RawUtf8(E.Message);
      exit;
    end;
  end;
  probe := obj; // from here the interface owns the instance
  // 4. the entry COUNT: an archive carrying an extra file would otherwise
  //    pass an inventory walk that only looks for what it expects
  if obj.EntryCount <> Length(Reg.Inventory) then
  begin
    Code := ptcInventoryCount;
    Detail := IntStr(obj.EntryCount) + ' vs ' + IntStr(Length(Reg.Inventory));
    exit;
  end;
  // 5. the semantic inventory, entry by entry
  for i := 0 to High(Reg.Inventory) do
  begin
    if not probe.TryRead(Reg.Inventory[i].Name, asset) then
    begin
      Code := ptcInventoryMismatch;
      Detail := 'absent: ' + Reg.Inventory[i].Name;
      exit;
    end;
    if Length(asset.Content) <> Reg.Inventory[i].Bytes then
    begin
      Code := ptcInventoryMismatch;
      Detail := 'length: ' + Reg.Inventory[i].Name;
      exit;
    end;
    if PWebTplSha256Hex(asset.Content) <> Reg.Inventory[i].Sha256 then
    begin
      Code := ptcInventoryMismatch;
      Detail := 'digest: ' + Reg.Inventory[i].Name;
      exit;
    end;
  end;
  // only NOW does a store escape
  Store := probe;
  Code := ptcNone;
  Result := True;
end;

end.
